import 'dart:convert';

import 'package:datahubai/Widgets/capital_letters_field.dart';
import 'package:datahubai/Widgets/decimal_text_field.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_multi_formatter/flutter_multi_formatter.dart';
import '../consts.dart';
import 'date_time_field.dart';

final SpellCheckService _browserEnglishSpellChecker =
    _BrowserEnglishSpellChecker();

class _BrowserEnglishSpellChecker implements SpellCheckService {
  static const _wordPattern = r"[A-Za-z]+(?:['’][A-Za-z]+)*";
  static const _bitCount = 250007;
  static const _hashCount = 10;
  static final _dictionary = base64Decode(_encodedDictionary);

  @override
  Future<List<SuggestionSpan>?> fetchSpellCheckSuggestions(
    Locale locale,
    String text,
  ) async {
    if (locale.languageCode.toLowerCase() != 'en' || text.trim().isEmpty) {
      return const <SuggestionSpan>[];
    }

    final suggestions = <SuggestionSpan>[];
    for (final match in RegExp(_wordPattern).allMatches(text)) {
      final originalWord = match.group(0)!;
      final word = originalWord.toLowerCase().replaceAll('’', "'");

      if (_isPartOfUrlEmailOrCode(text, match.start, match.end) ||
          (originalWord.length > 1 &&
              originalWord == originalWord.toUpperCase()) ||
          _isKnownWord(word)) {
        continue;
      }

      suggestions.add(
        SuggestionSpan(
          TextRange(start: match.start, end: match.end),
          const <String>[],
        ),
      );
    }
    return suggestions;
  }

  static bool _isKnownWord(String word) {
    if (word.length <= 1 || _dictionaryContains(word)) return true;
    if (word.endsWith("'s")) {
      return _dictionaryContains(word.substring(0, word.length - 2));
    }
    return false;
  }

  static bool _dictionaryContains(String word) {
    var firstHash = 0;
    var secondHash = 5381;
    for (final codeUnit in word.codeUnits) {
      firstHash = (firstHash * 31 + codeUnit) & 0x7fffffff;
      secondHash = (secondHash * 37 + codeUnit) & 0x7fffffff;
    }
    secondHash |= 1;

    for (var index = 0; index < _hashCount; index++) {
      final bit = (firstHash + index * secondHash + index * index) % _bitCount;
      if ((_dictionary[bit >> 3] & (1 << (bit & 7))) == 0) return false;
    }
    return true;
  }

  static bool _isPartOfUrlEmailOrCode(String text, int start, int end) {
    bool isJoiningCharacter(int codeUnit) =>
        (codeUnit >= 48 && codeUnit <= 57) ||
        codeUnit == 46 ||
        codeUnit == 47 ||
        codeUnit == 64 ||
        codeUnit == 92 ||
        codeUnit == 95;

    return (start > 0 && isJoiningCharacter(text.codeUnitAt(start - 1))) ||
        (end < text.length && isJoiningCharacter(text.codeUnitAt(end)));
  }

  // English words are derived from SCOWL 2020.12.07 levels 10 and 20
  // (American and British spellings), plus common software/business terms.
  // Copyright 2000-2018 by Kevin Atkinson.
  // Permission to use, copy, modify, distribute and sell these word lists,
  // associated scripts, script output and documentation for any purpose is
  // granted without fee, provided this copyright and permission notice appear
  // in all copies and supporting documentation. The data is provided "as is"
  // without express or implied warranty.
  static const String _encodedDictionary = '4MC8/+OVI2GZAsTkkgJwYp6avgfClEa1GDk4zNoNAAxAdh1y0ABaXVL6QIhCxNJ0hhb61KMIvWMdHmhJU2OllU2mEJ2MWAFZ0xHR'
      'EEgsQRXgrDicZDWwIygtskZjaBUoQgA4QkUVTAQFb4oKMlTVdc5G+izakFSMhgdqNQX+bHKPgQIltDwpLlSvKE8EtEIFpJauNCqD'
      'Woh3AJaqhoCSjjhmQjiT40ncrbjIMJNGEPHTgABK8AxVYoixZ1BTK/K9AoZwIthkRGkAuGFjvQlmwUbAM2Q6MU1wHIoakjJwAfaE'
      'DPCiiQPGoBRAhAdMbaq0INRu5AgiEBBzRZIcBICMkBwNQVaIFawIxEnjEVryuFJHhkWvVN3ANwwSpjFVlWvabgIVFGdGPQQtDBUP'
      'Nx8p0ouopEUAYgbAMPUyzCQerhxNesCRnFops4NQollwpkxD63KAfQTJtimTLN0ScQpraidnEFKehCWGTDg0FgIwIAPlApURQR1E'
      'cB40SEJpoAA3ZWIy5kD7jnhoW5caSEjZG6dbBEv+KRRImp5wAcYng2bLpAgrcBzl4iNFDB8QTZK7jm2Qaz/2GDgLFMHKLALIe9Hg'
      'Ilg/oIqWgYZ9cA4IGygAbxhsWWco3YjEWpCEiEBMMOLQBBRKLOSaxB9BKiCkwMDo27SKxo2occdgYLiYPBEcK2oZBgESJekQdx/T'
      'DxRoMyMsF+DFA3pxk+RwoIkDTp05ZiAuEoiIEIMFeZ7xl4eEMkl641hQCm34iUcLu4IvpwUBQaqbSLUiQ8EEEgZSagFYQWXdXuNW'
      'QAx6RBKUBAdWUFC7zyAWI3cYL6XAxRapgPIRcaNCQVIKGhCRAEiCqEWcWwA2LATgF7gAY6wPnynUUpIELDZU1JgE9BKIMmD0CDRw'
      'XjKEtJHChvIaFyqEwShsYMFKA6oTqYH57FBoFZEmFHoHwCfMJGUIpaAGpzC3IbSF4GSRAaQxApXSBf9AFCMANAK97QkUB3hxcEND'
      'AHYAKlKwkACQFWQRRFSRuP92hVQBTpRi3VuBVtA4ggMR0A2gppJdzFEhJLCMsC0UkUPjrBicpkIKBEGBQRfgSEjRIeCEo4pABChA'
      'zErA2CqnHA9gdDaIQigZB1AAMCSVU1YWwBkKdbIZVEmRE9qY3jMAYRKDm2qYA1BgCJpsUzCXEQHQD28Dx1rIRHBSNOMXDkznceAQ'
      'EBhmBwE5CoeOBgQZgjFIG+LBIARpMpQAGXdx6BqE4QjFCRnjoBgVDLQVS1zJaYKxKGkQxHcQoOqEryZiMjrtoIDGCrtEEYLYg5Tx'
      'ZmOWPlUAKNLbBbkTVHEgOhLkvgifEjINsE0DYktSgAqHSkc2QJdXcAjRwCCba5YYmgfkksJkZskDCOZGPGC0QBZNZClo4Nr4zhla'
      'LKxBAOYgnAoVHgRpc8JkKFpIKAduF0UiIHLHmJEyjxJIAuF3BgAHRgzDYrjFZPSD1gBTQbCEE9B0AgdFNC/TUSiK74rVuGmIJ+FE'
      'goJ6JfEFOtpMuoFgQGmSFE0AThlBpYEaMOMIauF0qyVnEqGLmH2s1phUiUjuzJKa9Ej4FVMQLYAG8x4hyDesIH1GKmx03JBakVH8'
      '0AnZoarCYUkYSAD7kh4Qcenjq4raYIp7UwRGH7ngLFkgAeHlxbVSFjFhDWQbkIDJNT0TAn4snkgVAqICuqzGVjCpUv+gZrcTieCh'
      'CCo4ReA0fon1EEkAEvUEGRBBIDWlQGAiWTePik/Sf5yoxZ7TyhTuZhsAqtcKYcTQ4eCKW/xkQLFTrgDWWeTgYopRCBNBiwQkJADZ'
      'uIi5GTmYm/FtpRuj5eMFGISAoEB4WxgcCTCCwoRoQDJfUEE4oZiCEwGBmvkBFC8gKIgmKpq94uwy7U4sDGFgCogx5gJNASUAy+Ix'
      'DC+OEMBckQCTpjxTs624GDFgm/dAkqDVKkKiNKx0kIiLLOiBFZBsBkfcqZGGgOexAEhCW4ADdYSwCiPFE9BRJIoT4IGe7BTROgsQ'
      'SAAA93cxBIxMTxDAgl+CBJVIcImeZEwedPrLwXAIQCchU6EAZSeLMAHkTwEOKZBKGIcbTLLhaIawzL6AFKQRIwJJE2sIAACiR0K0'
      '2KPAQWgDSgMaOAMGcU4vCZ2kIFCJoO1pzbrrASQDWB+FlgstA+4QufSMAkj4B0qEH+oIaiZ4WRENE4wooEdqfQoKSFJRGtxTEV3Q'
      'WUjHHPYW7VhaOcB1yPII8sOGLFSy0BI0qR+hALJB4VoDYdh8SHzSiQ9IEv5Ug0SdJiO8bCrGJO6JhzyBgN8ctNOLyAA5XCbCCXgi'
      'oRhQCvyBjeRH99kxcRKVAeypAI8wAidorwv7AOBYCnGFXTwrIcgAoBEEunWQUUSSRIEUBoA40Jt2UeoGI0DecARGp4aUAP1FoYQR'
      '0oMGwe1BwgZ6dxATIlrHCOV3RZB8RWcjeBChwSJF5S7kS8oJQqAPQMYsM5VCTaEwYsoihZhVN6PMGDv7lqpcAUAs4wh2LhIcT2OI'
      'AWR09kB0kz6c0iV3FKFpXYqqsHlEG6sA0JrDqtiiQHfoBUDQ8dnYhIaNiMbDNIAVglCAEIMzOAjUBJMYIVshcFvsurrgdjSFHOgC'
      'eJzjRHvPACqBBi5t2GTgDklIXaQIUrVIBMTUk82l8SQCyEosqyIi0iB5pVHigVIhBVr5sghowFmyvzAD8giHSdFKOOtOSpoBAeAo'
      'OBJ4K2CHIhvBGE2SMIBhTfzwmVgCYqUDDXI0gtOkCtmUrsz+rCbYfabh2HR5PCCG+MHYccjpif7BoZgAzgE7VcRFJFCFOFSItmGn'
      'hjJYaqDAS2ocVAsKCxHJoSBUWDKH87WQQNgA+DHTQyIQgAGTbUoCmHhwkgkCSerzHGadxx5EMFeMpFhEGE1W5WiCJXp8sS5JNCFA'
      'GHQzke4yIgiTUNFciGoIFeFbghvMSr1OhI1I4ASQeSKQTWhw4A4Q+P84weHgBQ+W1AKOViaARVKZwc0lRJDeaakzQYz8potJa5AQ'
      'MBw4NyAiICjieSC4hQCjQMo0rwFnd3kNHcaUwlt7ZXAtjIlpuBqgwjASocFwlo9QUisBbBB2SyNHCkRrAEEQANSzFEJUBASTAJBd'
      'bRh8CAUk3Xc2iB9Csrh20YsBwSBI6E16l/Si46VOckzsW4ASp06goQYIGK9ZuXdA0gtSkbmhVHWWgLylae8gRsftsg1BZgP7SjBe'
      'cxj6LhnwQY7wQHTjRndBaYtF9SDFQkxnJCD/KUNFHClDDESnqOs2YgAjAzQLNYLjBJRM+pfDgUnxINrPhkDB5AJQDf1ZUum7LMNI'
      'wj0JBiJRWpYsqwMI3UHAdWX4hNElSuYBb6cC6/9xu8hkIJyFAoNYCTbMEAG95fNFXAlygQoJZQoagA5wJQxzJHGZW38SXBotDETA'
      'iVNFLiqcu3xhpKoAioCS51iAjOGyxvBVQa/E9CMxLGCCgTAWgPR6EHWBQGMJUIMZ8WZ7QIddgRkEFBAaWLTBAhNBQNoHs8U+YIJA'
      'eSCiAsBYA7PAuSLUTCYZsNw0+DbRTMqSdCD6vBInxmvLDKY4BOBiAkii1gB5RJt57bCHSSIRYzi0jWMhwhWwOCXbXXIIsoE6xM4A'
      'QB+2KDE9lDR8hXMyCGNScA0MJiDjUowDaGwYQDmSQ7G/AjHB4RCdFQBTKSrmRARnjFIE4SxcD4U4ARyBQCQqgIBvC1ErEbqogXgl'
      'CUaE39jM6zrH48Oi3GgKJlBE7HEgYJpoSS4ACDudqBstXN5CAdkP1+WqrDEoGRxmI61+WM+EJXhAJFD4RlF0kCgFYSyWM20d6UEM'
      'ByQHMSX4sjbeW0AirZBrvTIBYEigCizBkJQpEFEUoURSY4AEAlJuY27QA3upYEqE7JC8ToYRkXjk+YALFBx6TNzNLUEALZSUxYQA'
      'aVbR0VQICbkYasxoKaAObSxqXm5TsJfCSY3chC4HCBszTPU4AC4pOEQbnRCpVBMbSgiFMBwFQJGWRAiSPxRLTk2l3Cec4BWiBqer'
      'JgEIgNQOfIBHEKai7LmhzAZUqSUzGh1D6OTeXJ4I6ZhWzAxQ2CBhHg8Ix2JyigZPYnLCdaILdMuOASkKzrKSSBBMOjiVjfglA6mQ'
      'RQQgUQllOhG8WsyU5EU4RUjgkUnJVS2S/QgMJuikSKWp1sVHTxgkwYnURMEER4oGtR9FS1kF0UIcgOBGB8EwgLAWuPABkq5KzCAm'
      'MOD56MNE8xbpCzQXgApcepcRQgys3ATKZOfIG4heno9whDNqJZ3mLRSyGkFvIAp0oxLIiGYpFAIAEYQ9P8YNEHUlUUIlQQSwBeRK'
      'jgilY0ossN11YjKwmQsvk7wPoJBt0K/YdSvSYJ50KCkLJG8uYMKN5lLGBkiJYmNoZABEhzHNUQzAxQJBkbFJrKHaJcNlEIVUVxOg'
      'wryE01VHzHz7XVp08M8pySraFlGOUKAoTNKQkSWIwLQrURTEDtqLSAmikQgVB6NjwsgHGWLlRtGG4tWIIvKrf4Q5bwjnIlISgVVN'
      'kgYMJm1IUHJuS9ZeMsilMtg3MmQhdwR5ZIpqHqDZgpejpBQYACkl05LRJAC4y3bC2o8Zg0g7C0AjUwikEAjEnKGsjE2gAqDgrl6J'
      'KCLN9ALk5VFRALDhEIThoLsmOZ7Sgn0Iqh8GYIQIMQSahIi15k9VsSDRVk6/Mj3CkEKbihxTAUjEDU6TlHGNd3zrJIhdwDgkBJDB'
      'QNNACA4VGQGC1Q4GgqSS1QLAEg6uUZTAxkmUCAcBywwEhAisZKllPJaTZACXQKvkCtQvGIGCwga3iBOIhEAagAiKFghqwBY4UBY5'
      'IzC7zsOAU4CVxFiBBhKnUkvfNeJ9cX3SYB3WLRtYl1vgD+IhYkIBDI2AsAAEAZ8GT0fKP3CdFZUCDKQaHCi9QOLgYMpcQ1gZkBSC'
      'A+hFUyBMIGD2lMykBEgQSiHcjSYi4swcBB2sQyaTK7JJCGNBWY08uFSKOatl4v9XtoIgEYaOCBQBoBlpHidWwmWAnYoVGmVtLQBg'
      'EEUdEYPMdsZgCCwEYYC9UUWCrQ8eUdJgEQB+yyOeVMECIow5ZuuBDsxiF7iVEeXGKBkvOIIhLiKkwqZGHOTLHYKjFWBCcCtVE4qF'
      'KpQQO5eAlCTApKIjrmFAWGXBh1gBSjPgmGBAFDA0MRzicAcDFtdDcFE4qb2NK8sXfg4kgl/WBB8ohANsGlEvg21ZZkZAcWLCVEB3'
      'KwhkyuBgDV1FKJ0JVuCTjoSi7hHHWVhMFq0xIRDrK3sBg0FYFoYD11DI2AgCQ4ppN90pSGCllaQ3EHRQEBDBSIThBVXUBu0CiCjA'
      'gkCoxsUm5TYweKYREE2KYJIQCJaOlRWo7YlsQkZgsnV6g3w9L4f1JDixfakkLhBZjTmEDxkRA5bGVBkEFLAgZQtij7ggRSXOMBGt'
      '6EkFtTHVzkgbSU5JEgvlEMDgPEACNMQCaEIOxQA6B5h4MSGLUl6iAAqTP8jYrIWCKnTE/UQAgeKsgArGEcGiVShBFACZhoAlV89s'
      'WnVtU4jYhQgs6AALaQBGE99uawdwgVQGAszbhUrlPZm6tJC6CIMGFg4FZYvKAwhxOhgAAg2gATQYpnY4pRYVBnUA7w0nkc6o0jKa'
      'K/kEy9hHIPh1sidAhIkeCoUiJD3sGSRQkiYDBYkBGo1NPO4UQCALtFw5JFqkGoIpjJVmKqPBrQ5qnkcANS4HIrRhkADkVT1IejFG'
      'Iyb1TRy9xBKtYTsc0AUsRIZYNrTCYp+sR4qgkAAA+CM6zAirgg1DgcBJW4qIgWALIoABX2BNSkgWFCJBih4Ap4lpcAyQSqnaoYwg'
      'VyAqMNIpAnFgQnXeX4CWB3XoFjmqkBEIGsaVSyk+5QQBIh4AQjNFQix/AkUnUIcpBVIm4yOOEtwHjBQgHjAs1HLwrApOVUckLMMh'
      'ohpkF/ZDJUIhoCHgTcEJ9bXeyHdKghSiomgoQ9ACnmCKIDBgjCXnl0gnIhg4UBAwO5hhAq/ONLx8wwAiFIW0sgmkQrEnCZAYZU4k'
      '5qVGpOjQjOQJiaivkJZVzFAz8CvsYhpYKAwhFRTAAnEjgabpBnDwe1N2EIKSTsFPbQhrggenbkIBByEIoAMlgRHDI3G8wzzaERlR'
      'EBoJJEj55QBfOgPKCKCxyCegUNRsZmCWARmGZYgWAMFg90oCg61ZlFiZkUQQ7UOKuSuHJSNmnRBHO3cAMBkFYKVCMOuceZSKIJGr'
      'ezEX7cTtmIAY/AFsVIogGUgy4fF1FWctKEF0gSeAT4qw4eAFCStS0iwhPaGCFdHEtm9Vqd+gbeSoYVdgQOybAhVggeUaTIielAcK'
      'AY0Pm2FRXb3QCifICnWkTZKO2RYa58klcZvEQzqAy0hHLF9sEB46wJnBRgw05glZRisUi+NBCkQglwvwJQUozkUMuCefAI3kroAR'
      'yICoI0UBCEoJq8hQikprTAPXUAilMQQBaYWD9ZJAQcscdJhAXMrmniqYRcJEi3WUlAIkKCAuJMAqAoA42dQUpAEojHKAJW25gBg2'
      'hBjkdAvBGJu+6KEVypAmFvjUwEMYDZoKAeIDdtbQYQloEwEawiDKIQytDcSccU8mKpyJ3OwDnzKRrKqWqiuxzIPw2Pe2VLqViuL3'
      '6KJUowfREQLmCtGQiBHGKjWFbEEIWcXqIA9UVMZ0ZVfyikAggh8BAYcGEWroSEEgxhPZiiHqApgoICGCUbrYgO26gxttpRgvkAe8'
      'DmePxjo9TiOiEFJg0SoJZCJhZDABiyhXwKglImBAIwA7h1WVggXJuQkfurBFbQK8h0T0sAoQRAQTCOgwxBWApocIkIhY6mIx+N2t'
      'eDDYUbDP63BBMZLII1ikHijwQMwNeaFgU0064AUgMAGYAQ4Th0oEiAxJJQIGWnYgMzMyi3QoMBhXIFsmMlKIG4RcxAJMLTI1I5SB'
      'NSg6lYBxrPQxI2UcHYnSrKMSQ/XQLRLDUNI7RDh6kr8RPSwAuEVaAuUycWAUswZMgcSSGrcUU+44vXB3V0HciQMxwgjYBlINHKC1'
      'pDgikIlss4dhGlpBR7JqEwgVa21G2xN24IE6IBrifgsAZLLcxiZfJOwmgowfAAHsiAOAiBk/WEZSOhE8eUosKTXmBUNA8UFWSKsM'
      'MAhlAEAilj8QOMzYacALSDG3GDYBz10kIwBERIhQCoqICh1VJwgVZ6RB8CLhlJlCjxFKIAA00EB8kGA4AnyYYbtIEtBpwSK8KgHR'
      'thSsglJ4RKBEEQQJFSvl0+FmIkJsYdLYjsEfSBiPIVJBGNC1AySAmIWs4CahoAfCUS2UFCeoLN68AmRxiyKWQOugAxgEciBjDagC'
      'KiBAlROlqM4UoBnkGyXRaKDpPlZeTaElbVDzwFIBQgwMIH8AtIUE01JCJiKmIBEAjRVP5PRlWgCwHA1tCQiEJ3hBjAwRh1ILAnvJ'
      'kX1HlIEFjgEjgJEZl6CcJAA6VYGkgIQl6ArlByqOGwEgCBJFOZ2MDBK2owZccELzZEwlWKKBwW2+5woCFjSFdsKcBeapLCjQ1A1Q'
      'h4zZvEPOFoOtU4w7Q8sgWciGQMaaoAbhQkAEGahrwCskQCI9g66hpJ2rgmnlIMT1hQDPgm4oYqZLxMAuAiRAoBMq6GkNmRg5hQBL'
      'wH9JEKhCBgAiDNEcV4gAjSJ9EIAIAXC2EhPx6QVYDwgTQT7Gg/4zDIavzTWOs4PpDF2j0+IhtRlYkg8xwKrN0pCZSVNGJoJ0MVMI'
      'hqgLhDhYUOpSJsoprLeQIQCuDUAEJKQgLBtSOsUAGBAQSeuGfdz/DkwCWCuh5Q+yhBA8wEpAFbYJTVz7aCOxbQPmzEDtsIjFFOdM'
      'iCJt+CaQGSB2FUiQVNqXRwvvREtABJQ350QWuoa0yiEjk0IpCkayvCmAiAZh+DPkQKk2HIJiw+JifwPQiMQAhupSUlm0SlJOtEFl'
      'z0C0jVgDTDMOSISbXUnuBTlmghBKeILlSCCC9CSR0hIgARUs4DMolVEUCAzDSslaQ0CT308FKH0NIQbokAQmJA0EBT5ditdlKHcE'
      'PSIGFuKCxgoExO0lAEIkgS7MZAwQUE9VGmg0Wys2pzzhVd6DSoqB7sBFNCE1KnEXKA2IyxKMMFAyyDBEk1BYCMSUNIXWmiqg8inG'
      'do4lyG0E9GVkDu4QDK8NMQfqW6HREICyNOYtDQLFOGF5mUEAxk+YhfoBR1QUYgnIiQdwiaMuJ+8EcVUswQeHGRKAyKghhAKpBb14'
      'D+CJGg/sDKIECBGB4MgJJJXAI6EJEgSgwKNoa04/AMZz8oSZD8YwQj72QHASBWtI3vySbvJYJLAGqZFA28WaJEnAJsCYC8EqUjJw'
      'VHAnE0o0BQ52EgtcJOpDAs6QwWkPyMxFB+TC9N2MuwZqxTsxrjQYwTiJQDqLrKDEE4IwVlA7k7EJ5shdySgYfD0qCK2RtJNhaIRa'
      'UhBCBpYAAxAKRpGjUcfw9hQ8OWAAZB0AWQVDj9919QqZjBz6NimoGRoOgkBIDAMiqABuQBwlgAvjCvChwNccWTXIcCkih/HYRCcT'
      '+g5mU5GIegD/iAmpWFwroXHKiiopxBJwSAmA5WaeCa1JABAALIBMI23I4NSMa1HDqkFSFJbwsQlD46cKIlD5xFvbCIgMsrn+cLQE'
      'goDgxsIFKkslXhRI17iYOqpjWEagkZ+1fMA/gjEJgqHDMngqRc4ZXMtRFBhhVoZGkq4lRTcSMCLfIkip0hmKhQRCSSAQgwKEYWgA'
      'lAC72F8JaIAARgB3AYmUmYxrAQgpO4kk8Sh+DhCMiCMQg8U1jhNTJloKSw1UoTBgYMBmFAnmAJoRnVSK5OJQQKHGe/I2M9yiREJV'
      'QvLAiwMsSXAcfw734mRaCJLYiD2DSZMcuEzJTQo01TM0ITEOBMMR0NRWl+Zf0iX/iAvpgA1GlPMFVB9mi8YGjAVXIaDbQANlDb9X'
      'M4P0AACIBGjCkQZArAq4Kl/qHALOAl/ymPFiCDFTuMMhCtcMkGA4wlKayjDooOnSEMQ4JWDLipgOOOwPLNdpEwaBixSOEHrORAFA'
      'xCADVHVIBTpoRPURVH5N4wESQIMhc3ZtrgOQQjnCMHgJBq6ysEEEAz66hUYLhgbYVm2gcJ0N+gKjsJgPYYi6w5CGWEBEDigKYBDY'
      'TmtAkqyJDl5HyUQJ4RhSRyEndzZgiNbSky0YWfBxZgAk0mCQmnIgFq6ZKA3FjFNOYTigbAlbGU6QHGESer6QMCQlky1M1IRbRt8Q'
      'hBB9gS55wMPJdEFP1swdZe6g3LNYC8A9xgmCJPmQ2Xgh4aypNFtlwIHiffkgrfLunBzeBETmDB8eDDuINawCCkO4BQ0hZVewt2A6'
      'DVeuIe/HLVAKLSQwrbCLw4REiogRPJzw2yqbupNKV7hjBQAb7GEVfKYSRBdQK6sDmtq49aHtDPJfxj4RUUk7BnntbyitVqaB9OQa'
      'dYIc0FBgunYKM+aOaGKBIQYqHnzP0p0yEg4whOIFtwgJpioXATJCAaFs7EpW2ukjARKkSXJUxAONjGU0ucFYlYHhMMtLUw8myAGA'
      '008uxVwlpZ1QohdQExoBQ4Suy8M+NKNewXa2lMiXRPaGYgTpgTqIIPYqXPCaWVKVYk9Uf3YMLQ5vFZGtlMCSsc88gPICQWhCNLg+'
      'dEGSwmERXKQQO8gkHA0ceWfDWOUFSJl+YrQCDcQAVYIjU6DBTaEAUO4MuVwOQyFJkESr5QPgiL5CDOXYF4GgSUElB2JADj2olFZ5'
      'GEPOCCARcS0oUMJ4QRpJgQMAgmxyiwSVZRBONkMh816QsCg0GmQwBkVifyiiN6QqldFBgyQAWJSABKEMAyQOooSvCYgAhGuTc+cX'
      'VetqAj3/2aLhaEFyWutTeOEYEnaAsUP0U4AOnWDWINQ8MDjkG4MYdRlUU4Oyo3EFIL3wQFLmM9OWqGCsXAyjA35qcJ0rNRMhV7AE'
      '5SRlKoA1Uhj5B/IzhlH0QjgalmxXYtIrMI8SgEws24PgEbqtcZsRKMDKbBDm1zcg95R5UweJQEuQAceiBmVaJ0TwH4SxHHY/zzuQ'
      'JLKJkPaNA+lIhHZvKvbX4b5a7B5hQXhG4esYkjFUroEVBoWKREDywt6HIAEAHJCkUQFzBh17QqDXjhTBxahhssQePphKBjYCcKGK'
      'u0gYN3Bh+dqrEwB5pAtFACboQ6h/EDHZM8yFIRYpgOhSCiFtuSlmIoLGR6owYBHoJNSNCcEvgV0giI6CvWtOR9RAcAO1dTtHTEzf'
      'JitEQA4DtiHUPqShW9UyjG2WPvK76qLellTDDhgHEkB6kABUFIwuC7cKDDi14MOBNxBuLp1GHYhWT6BnBSDBCAfIeOlGLZvRVS24'
      '6HAxY3VPPGGHo5+fFtAxIMMmOpqtvKRvMEFBiPGAdOGlEqAgoioEPHQaYIAvAwD8CQmmzA6bKXJXEBvPKIl4tsh2GpoRhKDJHAqx'
      'IUJPGHNUyAxQ5507UaQ+hcPhu02OIQ64AAgRZhkrRSggtiB2hi6iIyaBAlFIISsVMMqYMsVQmpAbVbHbmfJ7NABzyxgNZwEAAQeu'
      'gw0LLwCkAj0eE54xCRwUgVy0omAclAD8PvpcYjtDy3J3UEmogplDwhJlox2sCwncYn+OcEAdjAAHjFQsOq0CJcDzJygFpngBgggI'
      'gcanhJV/QIdegusTmn8pqM3MeNGhkbKKKXQE5vKQiRMgQIDBIRxlhlgBGBiEgnbsD01FeZTIZ2wcK+P8JBJLoHLgvLoBbue0wFA4'
      'qBRCgF8oWpxwBGMr06gBLKVGrWplAAKTDKH8sdhhgAhCDgLFz5bICuF0RKQmEzCMboQMlzjFrAEwSCVFeDMMsQgtDBJhS1qWH0r0'
      'w4UCQJYlSgq+EY52nyGeYKPQDAECoC58vI0DDgZ4poRKmMUCxQA8JNLQPBOwDMRTL0YygguqhIYuuQydFywvlPE0G5UsvAJvjWVi'
      '+aQCMBBDRB0is0l5ThTIrBFSjGwlhZ9sApiGkI8CTiNJULEBo4abPwoSBuTCIg6aUzgJZwI086Fa6g37SoL2cTNcS3ASANhhYWHK'
      'JBbgcIqyJOtFRIgREDPMFdEAtDM2AiK4WlYQUxmIqMAgscDcViEBYggBlaTxIaySENbBYEbUbcw8pRlgKUzfZgdpGASFSNR4Ig67'
      'sBC950RrWaKAEYqWG8abVsDaXdMhELZrURU7QdBBZQbFBYpVSOcGLCr5wCrAz274iUsCb5dLIOYtPDIywhENIFima0AIgRcJKAAG'
      'mcQ2uEQMF+I6ClMUlHTRCqPrW2hjpACCBEmBRjQcWqsRcl6azASfqyOl49IhEBwJYV0xI12gNA7QY1haxAWAJigJsD+rYEozUAAB'
      'Ul+YrEYDqECgnSRB8DCkGIkETjANcQ1EWAyDILeImaKFO8H6ix03I2MTyQPtRgpaGMIeQ/QBDAYSNVAZqmRQGTsxSvg5DDQALAGo'
      'ADfA5khYDrgCKAP6BK2NUvCMqWbOZO0OENoCyTZMJAbBCIAQIOnN1lID4AIgYoe4pQAipnwIIsAAUiI9vRkx/gKtQZ6IMKaQPD+h'
      'xM9boAkESFZBrzhJhFImphUoRgjGIuMVTyPnZmnUrEKNhKGR9woUACkDPjwUeOOAZODQGBqlPBGCJuDlKyWTwAEFBkwqQ4twpQIw'
      'ETQDkoWCMAqTQzdDwYAoXSCJWRUkJ4JJMhDCBwkSxHnIAMaySDU2OIVSMxbcmeTtCHEmJAkQNS9jFAExqaJTnPpK6NgEEIVBXANA'
      'x4JFtmVPovOAEnjIINVJsIFiKDcGKh+0BCjB1NlIooXCO8zpVHhpEWMF4RnPiCjSigkGtZyuzF8izgaJPbCikiVXMGwRSSuhGADj'
      'BBDdHkran6DaBNEVOGGdkXnFCoFQRoSgMTShiBEYKwZgvxpkWDCpFTPSQFA/bgmcGwYHcEegFO0PZUIqyvHX7YD4AR9G+UDqmVCb'
      'LSSgltCWSuxhYxAlYyIXM/6gMdwR4IUQZMT9/FJXGQJZsE+kPN5+ieyCzxSfJDXyNVcUSApygBhVECxPAjapXfKPpVk3xhMUA3SB'
      'B5A4mZUUQA1isRQhCqpQYIWkKdGekZywgwAOghCOBrEaQIY2JNqYKqx6ywvJaPukbdxt0ekFsHInIb348lHFAlgrI05wSkiTQFgA'
      'j3FqCn4JgHpP0K2kByRqHCg5oGM8YECTSJxDgNRFINcCunBDsEyQDvIABHAg94giNooLLwCkMaxp6I6iFAtJ0wskEQEybnRDIi+g'
      '70xyNkrhQgqSh5ySlX26WFLXDNdKLOEzBwP4kwh3bKEpUxQ4R/sMVdsCPwjgAIOZBHDsFCWFYGABgVETgAKGsbhJahSQpE8CAlRC'
      '9ID8gR+n6jORMDUPvYQckO5gxgsESyGDjIOJAAyJjFg8lkBIPocMu5bZByuOmhWMyBRo9FTqgVgAKgsUSxweK/NI+BQDo3ACC0JX'
      'KINkt6hAPdnwbql/o8YZ0FO4ROAw2mRuDFtBwoBECKJYpoPcAGCGGgABmBydE+fjKhtCoZgM4FtiyEUmEa48iJzAgFUCdTQBo7R0'
      'PQNzzYLF5gggST281iDQl/xUY7KKmWC8DHmKDvkxJVqG25AIfgItRCUcECBsQgTyoi9wgBYUxoYniiSI/kQK/APcOsBVK3bQYIgZ'
      'NKCroICxgJHgDAogCyZhNQcaBg/oUAmwxSXLgeUIQaMO1A/dBsPMQmEkSnWqZTgIlRNVUEt17TAoLEOjNGwqqFUgQuZ0M6SwoK3O'
      'GJHQZ5wJCXZe18Cic4kwagDeP4lILqKCGTcQ1DmMKIxC15iJawYaIQEK4ECBxIQPsUoaLrgJssHSeU8oD+YBERxBUW4jKmvOt4wQ'
      'gwUJlglFTTm+wMAFqAkoTsABDVykTyu/GLGkg8Tu0SCTUgvGE+PSKqYAhIA1VXbcEef35ComipohMDUAOzZghF1qmE5ByRDFYMYA'
      'BJIBNE2WSI4iYXI0g4110rJYthcCQgoMHMh0ZGi5TQqYZBcMQ/4ayzrbQ4GHoQ/AgDZlAQy1yBiaMSnUCIU4+VspFC1DolphAxtG'
      'KBr4migoNDGYmwx8FlosoXgLgA2mLQSLIWRNC1ZyFBQHTTSsACygGwAGFwoisfEYJLFZ5xIKGIcAqcqAQg0hVhSzD/tWgZtjOMQn'
      'aMp0HIYppQZSHwCiEIkSIQ4RCBTfuAFPAIEyQDzhRvwkZJgXIt0Egss/DKGUUwBzw4WQKbkHtudLCwgiAKZwmXiBAsCAFvTmSTVD'
      'wHDUvIdWb8ilEYfZHLqqd+F5Ay5FHCaKkDUsiE43DBaUsrqFNiFMAEDSE0FwGkNIYcMIKZhWpBjhCzhg/DsRFHCPmavsCCgGBAQg'
      'gUt4UFjErhLAwTVcW3UAEQxDcixSfgxwOUGLBJKLTjEWAkZmMcAUtuc8LkgARcqA5npFkIYGKlhSG4sITayFBRzAPQ2MRD8UxBCg'
      'iBBIpgQyRwAvElgiCI4AbQQSWh4hLhCSpxRgUY4g/gAGk8xoMc8m1sAQRJAAMECoAtATEjE7aAAkPtBFVojKEjqgkEINEJevwiwI'
      '0qAYKqQLFkJBF8FmPfOWY5mpsiEARFZkK4qwqFie9A3aNAFA0mqgRoAtigOtgjWjcyCCBL+YsnjwY6i86AdtYlwOANABpQoQxI+K'
      'm5UaJ0M6aLxpCbLgYSdgwSITwTkh6pkRAJ3MB8zgtfAYYEkAmeEADOzIZwCl+siRIhRNBQqiECQHrb5OUu5hrDlIyRRAgHF7HtQE'
      'zgAAtURKgAcGl96c5rvi1GjEiIR4PjCEgOAvHAaDY+UHJVGB9LiULkQl4VAYkfnlOQA6n+c5mwNhSRYRGkpCZCuqcUYaghACarz5'
      'SojxOfKyiSaV2AGjwvBY2UA8QmQmMBVAgIQe8XA7TPICpRrVXMqMVWkUE2tloPeHqNPTrvpgiabHFEafyVkWJxgcIAiJBoQx69Qa'
      'd/DNqbuclgLCOWQUfeBhag7RRDAIqVrSKhEH0CvoRmzBULiVxRat37QaWdu3H/I72NEsltCBSQOG3CIpGgBt6DCiYA9dATWMDg4Q'
      'kVQZLnEW6I50asjRZNpoFJIDCNLQ2TJJoeAvXohxkUA6BnkLUEKu8Zx0vklTQFDn5JBrMobCJZy4P4OboETq2wIfBYGuarWA+4eS'
      'INAxQqhCy3kLGFjSBko6gNBB/wkX1/s7mlRUNAn28ELiPH2jYkWWKZhgpYfpXOQVrGLQMITNMOjgyeiyApXdgCSCdQVGDOCochCu'
      'QyYVK4BGmKUrz2GsKnjlYhKxiUxQUi/CgXEOqSa3mpIEGkDoUXeAplFjjnsXCCKWXSiyY4dKqEYCIJMIcxnomQjCrSkEAzYEifAn'
      'l4kuWYQTpIZdCk/JOOFAQxXwB8Q1tthijHhJ5EogyLWTRgisFquMglFeaBGZVbihaCBSNgaOIBjdXcYaEu9iWkJKgUrD6Gxg/Diy'
      'BEdSALFQiZAzRdkC4K7iMRD8XSYZMIJKgXZkABmDI1BItY4Aqr6cC7NLGRHywJDNSaELMtKJ2mp04R0hGJMWkBhUdS3UwYgKhG1j'
      'RhHJj4DM3xBla6jIbZAlwzMi57oR4tAggQKEkjck0rFxDtPEBUwRQxJXZShuooZrokg2mT8oAgRDUMMcOo4PBQFEVcFFFHIOCIts'
      'RAuFLYBeyo9iAYg7wBrmWQAPYdwAEkTjSCtApRShQeCpG0APv7m4z8KEHsliEtEiWaUMOgCBiFIzJwkvBsIwJkMoRoixRGISOoLA'
      'n3ppyPNVtLE55h3kkJNhdyvQa9WFBNoLIRMhQNjEvzRdvoTTYTYwAEwC5VDhMWIGjigBIEgcgBgCixGq1voQVvADlo0yQiADWBzO'
      '4JbrogJUAsgjhHwIciSQji2LFUnN4DBSXk2gC5FFRd+RmnxJGMOqlgEFHQBKgkA8pGudkAaDK0RAcqhGoS0gAUEOQTAtFwemJUXA'
      'CCQCiSgy3IaFSGITMtIDgXCAS0ILi9boGoBxAIZDZg4KaUsgc1AQuEEZEcMUwUceF7HVHZJSEXBfwInuBW/sbBIMaZM1AoKGQlnh'
      'qIWjgBeUpwbegZBjeQRbCCCYhHoXsLKOBo0GH2wwQ+yEJOIEmkhbV2hR8QQTA3grhqcBxeRpBgQCBIAbSLQXmiukJSXBhdCcj59D'
      'iVQAQvks0BL1mQWDgIlhf7qwxQ0xCJtKjhC+8H0S3EKUzlAQEUgpKrlFGNBFHUbYHw7rsuFD53gsuAAMvQKWcaAiJJX3+vwqU0Qs'
      'cUJAMlHS8JKD5aaleChgklKFACxk0BaGVwBmh0QLS1QhNA0ofoAYlgDUOIKh0A2gNsGSDobCn6Zw0rxqA0FDUEnkIAMPh6/ySO4/'
      'oB70WENVaKlAFDKIYOgYxEgGmUDkDN6XVUYXKFvuOuBQ+ET6e8DgUhwkj/EiB6gA7IK4I10sXMpRuCJxY9iUHFHrmHiNJEAlrsYS'
      'ANiaUA4TIYtCAOhmt9paEcjCL5IB4/BoiCxCRomN3oSSFYswhZ6xFIAAwItlJTkbtYapBnL1RUqXaTOSDsuM3kUCQWB8jIynyDgg'
      'UOAwjYhgoTEifGJgUmApwTbMFKXFhLogLZnBGeQpagA8IUJERzWyIobQzAWyRiqN6PgxgEe6A8gcmKgSchbBCjlScw9da42DwkzP'
      'cjUTiuKAZBF0xhoBNftUCtyC2BJoq5CNvAYJmrxZmscz5pMr7jzh/LTc8rNioAQJZslDMIOmNiQMWMIlRi0JZIwhySAA4cgDOoUj'
      'XRJkkoIeZwJTRKHYLroBg6AZAAXbTm2TwIYlDJNQ6ThAjU2NRthxwuHNchAeKB0UAU9gFIYmlm5GFc66DSCQQiBk+OjnypentXjc'
      'WtPJplZgGa5OU5WxMDgdBmdhZc8fIYIlSIaZIytPprblllZmJwBhEpJJBfUvoYTSDzh2QBgAADF9GYYIv4gwWB+jZUUoc7tOPNM4'
      'cNNJADFOTDZ2Bw9FWNwRQEhWg1EuERqYzMnwMcgZEekcZk9O3jj6BADhw4A0o04wBm04xeCVMMGRMeAC6MjnB6NzRM1bIOwriT8G'
      'meZJC4CAVDKOgqdosRJ9kkLGIgUAacomYksxRzoA8QAIkEpw20MdOWtKZI6nFSAKyhY2SweEAyAxQiGYPz0UpUfWhUxUwhN3uzTS'
      'eoFNmmkGpGbmY9gkBhQBh/J23CbulIQc3GDtqIzy11ezjHdBd0LoHCk/dJsHHmAEBS6CmpSOXNAWAA8VZWgHCSGXoSg1akSlUpMj'
      'bJggxVxpQnoA2aX/LJXByFeqe+voQE/uUGAz59L/o/H4RFxFIwTeAzkgmTTUCGKCMVWoBl9SpLS3cBhyMKKNeLwlkd1AwEcBzS5K'
      'yIRjocQKWLz0IxMy6DOGQ0KV0jX0kmqJRdoKjl6ckXVedv7INlTxMkDUObXATmj3qVuFCARooKDRVRRLAK7G3RC9AlAlQprikEpB'
      'vUaQ1IKGYCLECQ4lMYwQV4MLC6gDhgg6QDrQrREUSwS0Cv8VtKuBIoUGq7MQsIdlyZcDRAAaKiWoWsrOn3FbCKCHUOLSHF57SroW'
      'CBMS9OYDkIfp4HEo8EFNg4k4gyg0zxxgeTBPJNDR74PAOljDhNmMRBZdXaYERkZIE9DIaDKcZGqUBS0EJRwf0h4cIG+dDByMusAB'
      'NWJkQQC0LnLYXOIROVBSKeYDCUkKLCVAcFERh1hOsIJhaXwRAY4OzAkkYoI3pLhTgoEsyyAbCEoFgIrHLAQIJUAJwkpmhBTuW7UL'
      'uyhY2FIyiBbHwJJCPYSIQi35KSg9TE3WUPgQWCXGYADQFGRI0kqTRg2v2xJAPwiAYo7o0EoAqWknG0aYoZsXZhjjqyRLEkwyIQhh'
      'UCQlsn0eAATBhyCSGSCGyeAAQIgSw0YBIEDUCtmlAbDsgA7dMYJ4WtowmM6EBPlkgUtNoRJIdg95VdxV0k+EVJZIagEyJwguOj3q'
      'NLnE66HagRzyuxYfNIhCKRCyHbpMNBs14ZTkROowcBZECyXYs0KRDthIyTSQCQhl6JDgHGQWDBwlJJD6yGoCVUItJGhOENEhYSDM'
      'DIkAGANKAUinNhNEUrotAmUGeIdvrs2jTYGqEeKwoArYefGTFuCQAnKBILD5Ir0o1NQUnNWaK0UC7oAxnaDEluAeBPuYa/r8QDhI'
      'qlKpuBlghQZgL9SRNVyDXYiQyCCXoIJXo6rmvNB2VSHhTRvHNSJvEYhXaAhDipSBBiUvJJeKNaRqMJxBbGjlnTHoOTYJXwLp6PJb'
      'GDFVjeC/KuwIAZpHGpwcZhGwULxNhOAKB6D8IWUsDWHiAE6i4eNhwUTIDG3VjbDo0AbgGA6rBAwcOw5K25xjRBYdadFUP/cKvGUE'
      'Ra8sCUFNBRIYtAycUMAIwyxAvEGTIGEsHybIgAmVJLJsqB6QdAz06VD1Jh9PuYMBnBIKGMiIA4qt2I7rdDc1yhppuvCSSEPxIobZ'
      'VkjAKtIOKmtgkAXDBdhwaZ4gNdGFaHgLjAo41SaNbUBBSGlOeyPEgiGnFowAGIAiBOyQFADpkBOORTRAhAXJdAEwxCtFsZlh2ltJ'
      'kMVppgAAYA6UNEAEQ0wK18UF3gCEQwhQ9LwQ5Cb1Bx9sMQJaFYXLl2Z5LlghHBtGNwY5eTVU/dmqqAkTaSWiRASnOpAZwsgynCxM'
      'TwgFFncSOMJUSq2MAsIa0OSQ5jobMQxpQNoV1ZQSNG1GYIBWuZ8QMbCSm5hKEBACOIyiAfhiC4klsfXLQoomAE3yChAADOZw0lpA'
      '5go6ylbKI8HXUlYRFjgyFY4NaEiH8pANuQYaQgFFvUBMTe0gDAbAgiT7YGUxGKnWEVDusIJ3Gw3Gy3pEDEAZBUJlSgA4y7JJ2DQI'
      'geHYI5Kww3cGCKTvFIB0SVGcwB1XywMQGR0Qyoq6ESmIZAJxy8Nlg/tfwKuZO0M5rAdKV2xIcYmJ8fIy4pggJKodknhS9xMhBZGv'
      'B+JsIE7KA4Hw2RW7HxqPRwmRaGAQiHYWC6FSJxDAY0EosQBG1kENCMKCBIHHkaaB1gOnRRMzLilACzTgyU79AKQpHMQokaEzS3nW'
      'moFy9QoMTTQoojQhEU0QcGoEBqCKjuIKM0uoEOARYGxMFsCQpxvJIHCZgFJMCTl6KGwAQKm02CGoFsr4PTSZqy8oF5kRPCwhBdol'
      'ghcBohI3FkEIFQwj8CSo5+xEsF6QVwX88iAA6AZZgSCgieAysyXGl+5ctMwnEVJ49VNTFyohBioRti0SJLgAf0hoFCWirLCgoQ8Y'
      'ozVwTcGiPEnq0SMqikgDNIQUikModSZkImlBbQFt5z4piy2jR8ODEVU8BIxLXAonOWgeWZhEAhkAjLAS6DAAu2IR00EUFA6VBDjJ'
      'hyoZpYcICIrUGUciYAmYAb9jhj2Z4mkcUQFgNZgHYUokE+ksNSQCwygEoE25hB9g6PkwAfWMkQQqqCjW+W4EhAFFE2P0yFSVkz3C'
      'CFquEWYQwCZ2RAQR2BuAeh1yTqjQCyiXBFQzcDylREawFAwAkCMBt0tBmCQ6P5QjlWDyWjYeD14Px4H/0RAlOObm0xCBnBUCy1lx'
      'zIoEUoRAhX2iFGZB/CTTNSGQAPPBDlOiOsLI0UL9CEZgReDxpCCPIUuyzCdtDaMEifEIWqpQBZGEghBYlyG1IowUYZUoAgYJHuH9'
      'NwtvZugDYpAAEvBFJXvw4R+LgYEyYpmFQp0ITehbl83GiLIqAiEBmJJTSdBIrEFxUe0QCjBmypKIZA4QAvKCCTG2FDUAkdy7DEAQ'
      'IuMsxiuGpBEw5hqBTavAC2UCYY4tQy+JWEilH66VVMM0JggKOkKrAmGxA47QNGQGUmQsgGZn1IBIKel0bRIAwKgghPQARy6LEWKn'
      'wITMJgAqI3KFS5gBOTDjQ0CYKJMKICuw2HwB9CKAC+ohMxxmuCv6vNkrDQRkAO4FhD9KaGBiBlCSCwCSUBg0hmFiAAp8QgikqlZ8'
      'ghyblISFQEkiFDqOAu7EIEUEOmF48BCDzosyclXFDnSOYebrNEutBIEEzAvuTsAQLbDVhajAkyUNsOQ3VQa4BmIW4xUSAx1tgLgG'
      'OVZ2bfRWDlWm2KFAgtUIMqKG+DGolw2ETsT5gGX1zPgWQGSUEg4L1EOJDEmlY6QAAFQQTZ+sOiDGWZDiCoYADEO+5iLiiBPhqRd6'
      'yEyIF5gDIMAHQ9qUTMEtEQokQlCHHgiRoFMOepI7uyikYcC8UBxCQM8AAQBfpAZJQgPBoQz+fw0EihOjEQg29wOkKGUBkQs0jtr3'
      'IoQ5OYY0sag9+wdYupCjPXaziXS4uiq8UqGAlJGhRUUUWR6MPENQAO6Ceo2ccCUSUk1JkUYQQVPPA1Q8mwDhigoQ1CZiPkPBgoZj'
      'zAmjKmCiIFeKcwobVtzb6ujSFjSSjQkjY1ERl1shIrEHqYSHMqCLh0AIFKrRuwoL4CYypCMmtEoJ7SCMoAnICm8QGhSyOAQvKwNM'
      'OsgXpmHQYVrtHzhzsdtvAln9oQA/9pyqNKEoCkwhsSU0txIzcf1vTI8kN0TCHeAcYW60ZrVu2GCApVQ+vaqaphLIKtiEOEN4Qkn8'
      'lKRSoB0RIG1GSIlxyKojsvg0q5lCWwkUEYRqUMIsLUMY9M0c1UlpYkJR3ogJiDrGgmAalJPTEDVjEohK9/eNSJVQd/HOcIAMLMWK'
      'YqoRCJbOkdFw0qBUtMsQcx0ROAfJZTEIE5EbIpAhQZIGQRq5M7tx68XlJghUZHzcaR+kQniW7UVohNEBgpNHwRI8BjJL2BIBDYwk'
      'BLEgEUJ2A8ogtzCskRW6UTrg0UgQELLbMIfQsWImykBGBRgxAAIKXjwpmoEyJhPDkNBMYocnAha+sWCQrIRaL6kdzQt2QOOE08c+'
      'A9IARbb4CCwopkOwPClLFRETAwh7DQJQBCMEHDmFgYQmEiCAxTMcTNOQZCbeHRAIABgVEsrGWYSsI8ZK2+BBIQlr2zRCwEsqAQCJ'
      'gFDAzMZKO8JUXOIQAXyRjkVRCNMnWRRB3w8XmKkzIVDhVwIMU3jlwxZNkC+YGp1HgDZmJVHk2o+sfEEYk7zUdMJEgrKqFCiWFk7q'
      'kZgjlmQAiHwgCV0B6Eoj2EhykPUFHGp5EQl4etAYFUkB6noAIWOLe7EkXPB3VA4RApCpOtQFSGn8niIoNMskJCg+w0YUi2OJmSEA'
      'SYXBYcU6D50xQgslhSjU4IaBVwjJFq7jYQqaWA4EeeTtIgj/E8I0bBgunMiQ8ZYoDCYjc2C8mJAJhsOYwyilIfJj3byAWCEQgKRc'
      'BQFlwU6QB4JepLI83uiYMmETAgqNUIClZEBgNxb2i1gBu770Ih/AVoQaqoDTAISimzhlJ6rMBiuWohanlYVRAaXHQCJQEGqAPRHz'
      'GB3CBre8G2xZJMQSU28IOal5GIFkBw8gHQh5X4GsR2OIw4+B0HXUJkAIDS4hgIAmvH3jCSAMCWOYIrxAG1ChgB4HVjgAAE0UTZQG'
      'gxJ1qyJ+NYA+CcAVT4KgRCjWuxSowT+ChkWBhUAMFRkc4QBeTYN3CExKAIQcx3aI+WnrAO4oNwUMh5KPPt6voSGxUwxuqaxIjBHg'
      'gRZB6iTVcxFOAD8YSN0OAytMENiSISMLgp83E08IKVNjiohC6IxYKGIlUbIoWBMQa0QS1ja4yMYSiYHGcmAKBqx6+Bg50D7AMgyx'
      'GPrBUEAdVkRWrayXIVBBk1lJlSj5yNhSOchseIm2k+Kepx5rwkYIMMQFlDW8AUglISCSEFyypPN7CU5Ngw/wy3ALDRdpEFAxckX4'
      'IEI4ZgtlIVKmGwEO0SNISvJqNMaGCbZbBMT+4a0tMDI9DECSY9UAiSQEwNPnkbnBEaCZV8gFwfCUvbx2Aj/RiPIXGXshBxq/jtoN'
      'QEDHBmw5m8wBRY2CT7SZGyKvBNwhSK2wtqDmcSEeE43aVfi+IQMN8kw0IJ4dBsA9EqgSOBMmlRMBekxZPMQBl0AUbp10C+J9hniq'
      'HCotzlLDBmIStyY0AJYmAJkjBDHlQTUoc/7lyooC8lJLLDdZIEDCiAiQhJUgQohhBQfYhhJQE2AwLowaMxqGi7SIYUOOUhLi80Tj'
      '5I1Nl4Kp+4iUfS4RSYgNlRo2eIWAFYhyDQxIUkhMGAEYzM0iSebxnfhrMyOFWgZAAKnCUOtBgWxYgiZIDIP4T24Agwc7DSV0ktsD'
      'U2jBgCE6EROteA28AjkcH50ZAUABVOMJ8KNyqMB8JafCZFMAnUS2cIQNRxXCAS3AxQFlAmgF4AFAICpMaA6qWo3QEkWYnCFZhhGJ'
      'Fiq0DRx7MZUHVHEUoxIgpO3iQRCWEZhCQAyNURgsw+kj8uIlZPRiMpkmPITF4sNxkoBWMMQT9CSmJAcF9At7+1vRogKScRg8UEMF'
      'ERtFg2giCgBQBrgtAIIqNVhAOIISgAzQbgi82lcd9BRUDvWeW/XqBBpB2MNEQuz2WNkpEdS4sgHHBRZGnC8CPGHM1ArEJXUBJBPw'
      'wc11JRYaBalsX4AYmKkbGUgWYAQGCEgyCLL2qhBmsxmQT1/wwiyGGh2UcE6TDLKgZ3iAZAGimMWcQCaMRugqJSAnIqthABACEaal'
      'BlZA4NkAgIOZWQ0QgoICfSBSS6IjAGJIBilzDColhCyAmxEJwpCuV3ZBJaIFttOWrpq7EeqSHmBqjtETmLXjBQOApGdTCoLuiS+k'
      'yNAQOAoBAkQyGEBIKCJChiRSbECT6Q76AjKL6A/GCuJbwvkiOCBlBNYBS3KHUJInCUtRxZ9igQSRJespE4QOU0wKloRJlREBvQFX'
      'hp4HuAYzAEAgOBoclZConFjQqQtUBEIQXADMxKNgtvKNgARDAImARksYMXQtPGTqtBMWQnQoKUoBLWSSQqcqICBoXaQDdC6LW0uE'
      'sKWEIplAtb4yRXE7XUiQE9oCglJADsOpbEUAaQD3QNFOBjeECTgKA6KUYOhACFHh0UFJ+YJSxYsRAKLKFQJKiwECyEU4oPBAcEDT'
      'HJQ4mC/9jYMwjOpCqUxhauDdi5x6gEYuGcorSKgUAApiaWBdCANkI4EvULHUk2BAJFcTJIbUPEK8mWgSOQqGiHX557Hd4gdFgrHg'
      'Y4AM6PKEAMEEw0J4ESJBSAoQQGDPQOcBSEoUwPqryJICGVJ5rsPkHlyvgpZwjBhEvJK54AUHoUEL7X5l2KVYkzlCSVhaQ2MNijUP'
      'DKBqFkV6ACG+EWgDgwsgMjUpkwHfFIoLwxjDD6IA3G34J1WQijcwpqaAnMSqECMwYCAgQGCQUCFiCB0c27ehCmCUIZJABJLwmNgK'
      'UVuIfACx8IgbEA2KMLmxNQEnTORsoDjYLKZ0YGqOiAdkHyqBTmCPC/1/nlPmR8F6oEACiATFrFbv48waRFsilCuTADICSIFBiSoy'
      'tRQNbIOBTQSvlmQYXEwBqlv/gCz6iWqFnAKXbgyXcAiYFYMkAK4hxb5sP4GYJYWxhIytCshhJVZ0BNFOd2IyWqKWMAhhquD2KE1A'
      'IrveCQE2uZD5wkDsSJtGQWhGlOGwQNB5C4qI5ORCNviyyxgzJdHKcHIbhR6DzWGqoWLA8Iw8Zj0EKABkQj7bNVqQnQoamZQH0IZr'
      'WZEHKSBKXIKkQblo0L5TGQkCABTDAYYJ/6sT2GmGQIAgz0AVuw4VT/JtUQQCCoWtottSH1SouMBETeWYIC4B+iGjpxcjiOzQDDLl'
      'qGWwiQzNSzjbDSsSCd0OZuZhh4SPQPNg48ioT7RCRgxpnHprx60tonlDhMzEgz0k0qCpBvQKgHuotcGaJ2Q4PEEIjPAYFqFCFAgy'
      'oGmlBYqV4ipEEZukjJUMeGDMZcysBlZzQFSLmQRMZKUuMBPQLJPnGoAKS8Ak1U9jjELGFiSEWKL4kEEdyyRANj5wiSU4LAIgIvmB'
      'UIs7f3VpKLIKD4pbWZYdIgWQoyhxaBQaAWZNwFF7h7SE0KzPEGAhcABGOSatRqQhaSbgMwkZel0SUYRs4eUMWICCgmLJHVEjWCRU'
      'ILpYAQHpBVDeCYkDuAYK0UAmSgFs5VNUSZGHJLCH1KUenoSQLhBmIqiigYSBUIXQe9WNtz7pg0GgMFSYIFAIHHsbZBajB8gxgIDm'
      'BOHC/PBkA5VhI5o0F2gBM+YEAaUsDa5hRAQVckUTNQqPs7EpoaWBpQ41Ka0D/HbIAgjCAmRwAQj2xQBYAJnUpQgr9/tydAcpJZJH'
      'qnKDAISsKFBBAwgpJkh4C6gSYpFAhtaIiEFWp5CxBomlFIjOHaRvwEEBGEr8xiIEbAYqkY02EAgIGL1rKII+pu/acEMIkb+WBHrk'
      'cttM2Bi8TAEXJkwUs7/DMEytxxPUGB0HmbIQUmwC5eRQYgOmbRGiJ4unmYAqR4FGAgXJKCFmQBbHKl8J0NjpMwTCSAgPQYJqDohf'
      'ZA0BtamqQ/MGhwkG1yTiEAAXSUvEVtBaayM9ijQiVMFKkptECYGBSAR2IKYqwhhMQjM1KhoqWomrvIkTDIEG8QMIOUB4hgwDNVbs'
      'ngiNQOXAOD6KcYzkClRkEFiAwEjCggJt44aSLlQw+ZXAF/D00ZlMNlLHAyGAKAZhKZblANsGCDgOkNHjGNEQODqUVg1M6lAAGD+A'
      'M4EyjBkECR0MyAmQmQxLgkSYQghxZeOVBUEDVVlDXKzMj4S6YdjD8o4I/GEQxUEqGCK6hBNCwipmQBQQA0oHQkjkAcyAqgAfYV7K'
      'ClooSBuediDOsA9A8QH7QmQoNG+jQxgoRNVDBHKTrkjihoHmepK6I0sQLQTDNEQGlcDKAFhCBlJJkALWCYhYAQYdUQOAnZBTlps5'
      'QKRs6sbCBBmCGE4gEu8neuZISKgMI1AeITRrAImBpyZNHoHPlBQCChhu86ixObVMcieIDQSAQmhlBRAgwBJCuqOEFgUDs1IVmzuA'
      'p3GRVCJgmJEHieOAnEJSOQc+EJUtnBSR4QBj8BTAn6azWQY4feY3EE1ZnxblADi1JQENxaMWCBAsQCac/wPjDeAOkhnhVSBduQXo'
      'IGoB1fBysIgAFO3Cogg4CLwotdtFiUzEZEG9F0N22SGY8BumrvMUgofJvp0MAgV3EYdqAQhTJOkH9nWuAddBqogzAYwaShu6KYpF'
      '/ZJAQjgmI2dja4QIobTiP73RmrnSFg0zATkhIpDQDpkboQFkAAEDASF7MFixCA5jwdjAYlAAEeYBBruxFjMTUxFPgx8BkAHpQfDj'
      'm7BTcAxCNBIiANxxiJ/yzNMXhDUNHkMS+GGhYYhQl0w8AYcSaHjFmNgVYuwRvFTNYEhkHQTqEYisxyEQRAasTQAqJoJuDgksg1Eq'
      'VHikKD4I+hGMQHdKDm/RejeCdBQDSG6kAC4WssjW40ZCIwGbgcMjGUNQtbzBdqyGAAaBGQR0cYxwPgtYmpMAR4TMs6ELFxwwR1D6'
      'SiIoGgaIiB0JUcG454HtYjHKH0fPclhmOxUsMjsFhGTQU6zYDC0CugMAir5RBEINFJEJ0c8Zq8SDoYLMXlkciW2ZAEsoGjSANrUA'
      'YwAHpCnIEyBbUzJg4QDCFSc+mk6DMxC0fhrYHDSiEjrDICHV4kjeKpdDE8CpEY1QgUIgY8ORRkDU4iLh0mTk9ucR26j9sS9ViCwA'
      'FNk3Ihk1M1BohsnaYDW14oSYdpL43QoxEI8IQ5mNF+QIBGDGDTBBAmrkEuWmNQUIWGAFiiANWWqucCgWdIZGUD5SACIshY1U1nZw'
      'ODR0YEXQEiJEEI+JIYGQWphgH7BSwKaNHxQYhKUy+Jch5wCz2Af9zrhimLCPlUQCEHsWuDF5tQgBjkapOQpG9aEAYYIFUMQDSQwA'
      'EQRn6UwlGQQCizjQBnhJzoUJVB4faBKfgyGvJGkHuMbUIF/YiiHUgiEMgmvAAAQOlFMEkHMgoFqLKeSVJzUE5CWznT2pyj7hLpSY'
      'B4WOJYR3rqBg2GhVs0EL0KBYBV1gkN7ARp5tNbAdPZDC4Sse0AIRN8NDbo/cRgccgqQNWUaV4axW8qBIEGU7Gj4vB8SLAAOCACVP'
      'Q9ZeqNH6CyjIAcCAEaDs9CEK4muzD7+sR35DIGNTuxKfn5CJ+HiKkgA7HMrIvRp8AMUwHDFgPCKAzhzufMM1jVCREKBQoblghsSS'
      'xoCa4EQuGFBcIZoGwxoRDHr6WQcA0gHwQJXuhME5By+MCECIhwhKECtkhxGmPRkr8l2ViY01lGUyg1JLENfJAD4DKV4BD0ALSwjx'
      'z4w85DQikgb0UrSbUbsOHsiqE+0EIBlSBRQIBEYDiXiEUscEdR1hBIzEcumJNJJdIZzCTQ00JRMBwRbIg1xLsjdKBnJJIqfPm9CO'
      'I/I5IDalEoGQuEgh8n8NknAJmASThw9D05YdYACSkZxblInL7lA/DUYOKkc1AItBgRqyKCFwcXZMSYtASknTkAaXH3qbC4EoSN0D'
      'cBfRlHcWjbJIwEAgGrgKpFKEmaUmtwIME8JNl2PjGkDA0woxGWIg6KXmgYMiZCKMPMG4pSVCVc4WoCCJx2oKMnavDiSjInDFhUPE'
      'RqXGBKMBgoHocC2lb5rEJTjIEIPARnmwVMn6EDAFCwIqr+pI1yUX0AtCNRHhhA/guLQquEoMAgR4idAgIJ0gx4qQMEwRCg1JNJ6P'
      'Z4qMAAcYDCiGJ+CBEQf3sqnM5E6pyW0vEbEgBawgCEMMAEwlNW4c2WVosOJ+UYuFsOYPM8nOaESDIOErsjwyIEFlgoCDktIcgF3Z'
      '+kCO1hzZAijiBNGgFUwRcSwYHvdUMBklAAYgKwQ8sBQSpRAgYDCIINhScIOEk3RmW+YBeYfHGAtGAhpZ74TcSO1mytEGY1Yxvg4o'
      'gLCQGHkkbliIl1RhkTAlm7B2Iw43Sz1cgBxFJ1EHiGD1DqjpiABQrU8D+dcdvLUIlCDFUeCrwMBBDIUcWmstAzzSgLOZmpDg/W02'
      'mZ3j0AwKEkvEsZCaAQIMAUtOaldyCIm2GLUQvRkUgB22hSkQSoptkYMQhoQ1gzAsoESs8jlSGBvuixC4jUFgHyUbco+ubA2BIeTK'
      '1UF08ACYBuRwBDQNQEYDLgJmatzLIKIkq4Ez0tf1NNZ4bQ4oKEfHGWSTAWgQxWfErhEL1CSg1IZ+QA9LBBCIin0pGajWZewUEgdc'
      'YAKGKtNCCVVgBSzGObHin4FmOSVcGqaO4H4IQ9Sq3UIQwkjXBqU0uZBjUKIFbILqIxErBsiBH0zpPgURpLFJXE0mYUNLZRllK4AM'
      'E0UQAnLA6ZRzEqpvJQ/MYGBmjhDQlSQG0QiB4UQbe6zhzD5h0HywigCCckiMWNa80xVrCTwgolhUVAElqOZUYUgi+CmCWNvJnZNg'
      'C4RckYtl4WHJeAURqCFKjoDIDRAwmaQUvokHLBnEO0imlM3AJkS2LjNmtlQKKnmNZurQKxYAIAxaCZxC44FJBVbOUSAfKFFAgp3w'
      'VlqkFGVBAKAwR8nJmCwQkNBkBVdQeAJSmQVIKAq5ABFWwQHcsPCZAYbLl0uBY6Mt2LONqJHQk0SZDgiVPmmP9XU+TQGr3EUMAiIY'
      'gZRSsViJI2ruMsbZG4EB8lc8OoGtUu0AtKXQ6oXBOKQGgNoKNiCZSYRH/mRV1WJRpnAeo/QdGAYBMjMT2wnHDFkIBhwuBjihVwO2'
      'AoNQKnurEUdjZSzzSRgM4MCt7PRK6PrwzmedNmgfK8IZCcVh4oOEEEIAyhIgbsK2EBqvEIPhXxQCLc7OCspFugG2OURRfRrAJQCC'
      'MvUAtECs9akDWDEICni6R3MSqgCNWi5oFHpeAhRN3gaxBMJjDQHZZ0qeiAsIryAg2PSAFUosuy4T0GypRIbbVfU3WqnpEjAmmpp0'
      'E8uGAQGoAVrBIhRezBDAlAScX0VCoIcH5BfooGP6MzRhA7YaBkQwQiZ5cEiMDhYhUG8pEHZlSxfKNKH9hJTYwmLiIhVyhOD8LATO'
      'SsUYNUaRae2S1pmlBqIJ8Tg3BIdOr4SJr4PyiqyBcRgCIT5QHogPs/J6RMCNMbmBoKPJoxQUoXjJzD27KIliH4CPgyAiA8nACRCl'
      'oBV4EsZhyI9p9NnZKCtAq1jBlhsoh8KcAsonlLZOjRSgzKhitIAW3dF2yOuEZ/MdeThGtNBcUmHUc81YJEJAA8ZNJCK43HU7xLfU'
      'fWfC4uOM4bQHCJI1erFXIdqG093gsqB4qFEIIWMTGLksMwEgKdoSj1FGXggMGJ48GSIUmwASJB1iQKs5azrgiZRZuhDIi4kAWgjc'
      'FQN2FKBCh5EAUHgo1GsBBBGwegsYRMrgIDO0M0GJaZCpAzRC3pkBIayQLqkQP7AJjqgiIo8kX7hmVtU/RcpTwAULEQi+UDDWMKKE'
      'wLZGFaaNOqAV2AtI3KboIRhDH7TFQFJkjKIzwOrqwUYRsmxaVGg1QauQRhioMilmGG22mgjgofIUW64VcA61mkZKSLjrHEmEEqIM'
      'JTUDzARxghqEu4SA4sFBATchHpRwlL9hNUIQmAwEUNCQgO0UGRfFoaCCKja+boQHkBhSoIRYyBwIAIWC84PKgAaAkqjrjWRELIaA'
      'jSsQq5GtHSjgwzYEweqqgFLoe48yWIEIlPE3FCTDKL5ES3zYTLNB2lgi4w/CIYSLNh0UUgN8HEoGf+0Lhi3UgaC25YEgBMUOIrjY'
      'PpyJCB0CjFcSCEAWqSHhosTSRZE1UGLGxw87SKUGc8N3CVoYnvLWNVRrihBSdl8SC8sh+mqOCimGpBW3no0AOUN3FAggGoY75eiz'
      'Qo78JoDUwOAGAIRVDhQGY245xsFwj2bzEpyAMHO2JZ/IgiotQ4h2vwSB6h0AbRmEwCjjiGDgUABIeuwJoeKF6b7U+BuPErZ0tAhA'
      'zm4vzIEoKY9SMSjAHGE6lBZw1KCgAaMLcyGdZAyEpTkJUFs1RqZlVj7HYo5gpEJUTGNwBKXAWKVqNkQTooJIWAAgQKYYUUsdvmOy'
      '3lOgZQmQNBc8AaFBmgNgQYqMplJIYPARFajAykgWBMPBD/oBQh9TYNOxwRYXZW5KI0SJJgxHG1FSol/EfGTRA2uEBk06UWDnkqss'
      'MYEXGTpmjEN4GnBHNkDkDRaKZhYiNI4jA6cEU3FE7UVWmRdpYFzjmQGOEJWkad1wCp0AwD5JlCyEulIACApQysAgSgXQhdp7kFpY'
      'wckXsGmqJoAMUFrMg4aa+Qz1dBGgXcZBBFqlN89uOwRpAH2gUlOUeYc0wWRSRjVQTlhkMlaRElMUAaJaCbIDGKPRZgFc4E0pEuQ6'
      'InBBHyDZAOJI/WjUXsFRk8cQFTzmiWggCr6VHcJ4TZzHBKArJib5RCSYl0SLwhtwJH88sO8N7QFRqSJNOUhfqj5MRiEaBCtGgKAA'
      'L44QAwCP5NLJytM081nMHSEexf7KqSsMVSyLQ+eaCRwNWwOa4z8sRdgmJlDBHjkRBnWCjmFDCg+UofYaxnNBHBQEJWXAiqExSZY6'
      'xmAM+WAFQ2JIEg8LlQW46PYSIjZBKQ1d3glxW3HQGZg6MhNZyYBxcBSugAVJk0MoABEYhR4GgDBCghALQaCeAapi6oCUwCcAqeSD'
      'ITkoiZhM2RQRZw4jRxh3ppmDhFbD84sokEiHAgGETCxkwmAWW7Rl3UDb6jKgA3bjCOYhSScsFCgWqEGNwFTikkYBRZmEq4qDczBo'
      'EEgIIAgCWAJFQ7Hi8WxQixAylJQdAgTQoYebQEbRSi40hoLCHA0VTwk+Z0GpGYgTiAYolHDaECiBqCg4OD3DwhniwAniBSm2QIAo'
      'mcAQRkl4MxBAQAbVODtHCBqQNeEUgCBwBQyS9QIQvI8Xg7pYRDMvwAgYDIKQKZZIwHDvH8rCnpMMDcUdCpFiaGoIj01KhMB5AUAU'
      'AuQKoACaJ8QYZuixKCWbFYQ0gEP25IlmgRgbHdxg0E2RB24FBnlEYwbmfKaQuZwLlgn2rwiIYJArKEL2E9hxo06WgdcvMNDhu3Dy'
      'oCQXFZqvQCC5ggVAu6Fw+wUhiQVAAJWBRAxUt2QQlKIk1IEhNIGmZDqExJWSAi7RIgKojkpHV2hAXrphKANR5UowZEKKAkCCUjwQ'
      'irFWi70mMoiFQA0xImWCyAXvYue2gPaOB2MTTOyn1yj5MCB81khIFgSBRB2SkETm9YUNioQMAAeQGkG0ONdAT+iQBoGxgfQnkGH1'
      'eDGCDCeXCkSAnWDGQwIJYQgwzYRA5DW1iaAFgosKXfMGRzTjgBQUGKCtVjIl+Dxk1W/o+CjYqF1NPGARYiJSkVASBAMHAVHCtYF2'
      'JLKbK5TINCABjq4SMMsvwoizIU1CiGAzABchsFCeQJjcGKGFG0SIdYk3gEjXOIzYyIxARssKA4NAwwREBsTo3K9EAUwmSkYibfgo'
      'gRJTqqGRwSqmHxAB1Il4ZKaXYhsnOkxGw0MFsOJd7lat4dJwRG0pz6D2k9vi66AMCwgHkVIIEcVYjeC1GTCXR0Ia9EKgzCYETqa3'
      'gCeBEWFDSOlqVocNAbPO5qzEVTLBqDKBXXM4okkUecWNqTDyVcIG7dERtoBBvdrJR3Za/1GslncsgAy4AkRBM6gKEVI1FhIQYrm9'
      'UowqYIPAyGPAMTxBCkALmgxgytGaRJhK+yQG8FG0X7h87U88WHavM7uGwigv966jtGXgKjgfsJZVsN03uAkeHwDOfbDwe7QQhedl'
      'ExRwa6NCIWIMPsWyfc57Jc2ZkOMIKxYIlkAsgdPPVrICAhKAJMON5aA2ABTxOYRDYBBdcOSFkgkYSceMeYsB6VYwIQvU0iHujmTo'
      'QzHiifkGWDMdB5MGdkwKEoIHITGAwhoi6aliI+hXwSyLR0vayJgiAF7fkkLzxutNMszCAnEhaDe190AcOWXoGdIdDIBlWTqJqSai'
      'Zww7U6y6KKdoSqhhAo0gOUygO60yt+AuykFCMWEbsJiT2t2iw2N+XYSRFLYalk6VlpxHCND3hJUg6LCh5NYGGxUuA9wXDEBEcLTC'
      'VhK2UIKI0zxFfVgHphPAgDm0KZMQRTthrk4TIGZOINgYyMA4QLmkRhKIkGf/ZkKIxvlDUdAmnPfRyiEHgZBa00W9wiyBB+HoI7Bp'
      'cCCFkgHoLs4eGQwKQ4CgZjUsDVBPJPSAAAIs25hFAgi9AEZzxKw0YlHAA8ZIxhN6QY4lnm2OoEGQW0VYSKvrlIoI6k6QqkRBSGOV'
      'umEOio95YxwyhNMg8PILUOA9MFtdCUibAAX6OExyKSAHAPCQywraFxSijUCJAjpOneHRBeVdQD5LYV10cEIlHnIyikAWlbQIK9UA'
      'mIWyDShAjOxCilQxsgxApZ77pQGlMx7Mn1RB5jSnAUWWyoGszbcVZpO+bufdwvYIxZIF4jvixpJRotNSSfCYhShuF4n5DjgcKhgq'
      '1yLxbIwMyYHCgw86D08MhOBB1KEkAD18Bglcj4r+N2n0hdAI+saQsP0qOjippZa9aDEwlg0JED4AXKGszsUJ92YmEfhstEIuANPG'
      'bBC75AKIQgJgEWIS/AAVRF4Axg5jQbVgqkkdQ3AqmYpCAKBA4PtTJoiyAt6YC1kL0mYHLmu71uEBBMlREj6EIFIg6kUARVJGb8Ar'
      'iDCMQWaCTyFFNATIFKcUHCAVkMRhlYzOY7m/NQjJQGXRgQJ2QHcJYADoBhi0t2S07gkLICCFwIAoYAbJY3GviJZIMQoGQwm0lo2j'
      'kRDaAFCFk4iJW44Y5aNVHGOea1iqc0yNLAvjUmksWy8B2CEAIpzD8ISoBTGNRo/EI+0llB3/kVFsAiSgcEKqAIBAIlpkOYg0OFfE'
      '1R1tk5S1RjUUSE3wMqGMEEkqGsk4xAG4rUMDNKC5zfByqBGowlg6IC0eLh6ANABhOMDwSHFEFCl50gaJREzNYgzjD5AumG2miFtl'
      'oFPkQqAEh0JlUB0oMg51HwJJmTaJgxQFksAVbe72xeAOTouxyANoi48ERwEPKnZicIm0KJlJhghHSUAjyHMjKHmnDg0Y9nBmA7kK'
      'SQVm0IQm5ANVNoIQlEwEF4RpB+FAcAPklymMa/xriRlmHEiAnZQYp5JBlQJYiZUw5tigC74XxGqAEwyZFE5YnBDcIAnpBBDPGGFG'
      'EgVMVYsUGCE8KKOVQgsIBsoQgYYxAqKo/nKqaSRu0QQoaNi0aAYhkPTfQCzC3s0uqhQWF0IF0nstByHBICalBMq4NAqk7QIPtHEQ'
      'AYoQRnWhSgI0o/K4QOF2dq7DBbq7OBjsCU00rdRcAKOCpxSzg6UgDEHohMMgzRhHJAPIijUnNRkkyoGuIRMXjKbsjNjyBYKWYUIo'
      'CEBQliEDlQEAPQBwTlaCuAYNSxNCqZiWqooDIk+1qFIDKgMD6WRgkIF0AJPjB8BVREutVoFACax3wIyNwOkxXiHeU2A7TDGzUgAp'
      '0kmWWWybvy4vTIRKA5ABvsk9CSFOTwhMJMrE0tskigClu0JZC4tIzC0CQQOILFBEVYOYSd2cGiXknYpAmuIQdeESRW2HFItqW0UG'
      'm9m59EKPBYEgbpCwgonFAJEDWgWfYzYG6xRsWRRAGLh9sUoZeBcr+hMGIGlO0YggXYhCEIEDcTCATICuKmSUBwEZYALCEOSg+ODj'
      'A0VsxTMEKcU2LuGODP5dGBgUfzWzwNmMddzXSSSduBGTpcsWAdD2uYO30OVEGIgjgJg1JUMKkq8JaTIAhCUAT0hj6wsYBeBFoJXQ'
      'OHeJqJIVczIIRllGeh8ahhnmMBYmQgFgJFyxQfADDoIEeArIxcF+DSsxgOsDgcaMJ6TIJaLAwKWHWKhCZEBKMDAKJE0AygEarAQo'
      'AuDViAuDegQYNLZsRsoEqwF3N0i3gIEwCNQonaQ6XdvzhwDWICkiAAD+5FwiIJh04KQ6RnH4USK0LnCNAGSi4WsIB2IcaSLFZAmO'
      'NjnzLYIlB+VAM7sMNc8UNhb8BI8JKhHIZGIjfWg65yEWCzKknU7RB4MKzM1HSBTQdWZAwjPgKCZIEtDg6izCSi5TCE4hU+ABmABC'
      'VmASDhXKiPIsXg4pprVRCz8aE1MlJEqULAg/HnxAWEEHFqERB0RH4nvOJwbYnhpj4JF5RxgjivYgBWIZCA9Bo0Td6TQZ4aBmB2Rk'
      'HsRoZFhktQx1rLfKgtP+BN6Wi0YMKCX6KxoiTkJKaOgCxAlYIei06gAfUlI3ff44B0wLQkCNIAEHgjh6AWKQRghIxQmClZsHlBDA'
      'ihBVCKnNGKzcljFOIhRXTYfh1OhAfoOIxFBekmQXqDRAvgLiDnbES8BZE+SdntxVKpAgkYEExSD4VUUZYfBKAMjJ3YSicObIbEAy'
      'qJh24RJ6Choxy6GMIxxxGQSwUFpfBgCBaIkCEmGKVR6rEOg2cI0gKKCNtICuN4icimScOIOGWUnhcWaSPoU8IiyzGCMNW9Zx2Cm8'
      'IvC0mgzmMCCvkUKucurZ+HAtwEDMwQJK6PMxqggEuoEIy3D6SoJ4ZYNCWaBRBIO6E9SRcLRhURLWEqQUqppAXammwJcD4FaxEIBK'
      '0AqgAiZgqAUWZDVMQKz0SN8eSgayCnNNpRMam85Y1KonJphqCIVjABBT3Kl29YIQhpeva+aNpx11agNybCqWKLxFHWp05ri3JxQp'
      '3Ii092cSouSp1fGUnCAABXHWhhkHMFPL9NEFgBjyAQzbGcwzwckH6BGSAkThX+HkFcGCUmT1l8wtsapEAHUU+RUdDQytLha6JxzY'
      'NEHLthCBIWm0qE97OxJSgwJGK1azZwgHdDEFoAiSTuioRK60lD+BCwaKijAOUCTwP4KUglAWKCgJNA6L3REwVdvECag7FCc3kDuW'
      'gKYMRoYpI0b4KzAOMPyAVm7JGTFKBZGRzMAjCxwDWsNTtTzPGlzGcICGRAB58G1d/oOpEjBAlPFgBSOCOfyB21dCqQcgtSk1KFqQ'
      'LCIsqIcPsomXDo1nQCkPIJhwuVAwoAmExgMx7HuhNm6FP4GGy2s8OHxStEMoNwItbZDAM/v18kBuChmJIQHEiCCOfQZC0ogSiFMC'
      'QnBDDMCW6acgimguYxBLsKkCC4D6ZNAznQbwos4haFYy0JapYgJCHmiRioZGhnoVVgIkKZCZC4URMmc4qB2Y4iAUxCruPBF2Bail'
      'RGDKJDIcDILRgyNqrEAacUax9EgBWyYAuAmkBSIVcAFQdCZBNA0Ywn85aiyP1lQiWWfhqQko8MMJmpThrLwRSv6RJbKD0AhEaIcj'
      'Nq3oYKCq4/+HPOBSCBS9ExzJU/UQHwrKqQhQd4yGfEeCkheM6O8DQ/NSh1fu1SAJHiACto4hhHBB3wVwgUIjJFCAMRVNKWA5jzWS'
      'rZDKwU/qRgIImKTep1aCglOyplYnggGwcDENIQSm74BIYXv4EACTLQacQ1SmGkdACqkgSUdW3iwEEVU+WCO1Yc+gdEcCAgxu0XRu'
      'AkLQFyJIiJyYcA3hQ2paItO1U8LEQwMTZASERUNwSQq7YRmWfUIKTBmgijjWzCqXCIlB2qA+KqW9YUGCJCQaAU8BqAjnKs2xNuAI'
      'yiKBargfmWgACImJhylJJsOgG2kaGUUyIwYHCoXZQUECyNQqBCJGFEeMwVEK+K4Ng2XpOTsAZHBAhUnB0OFKIsfGMqGfjHAeoRPj'
      'CVkocQUmXqtaxDeP2a2t4dBaHblGEmSVRgZyoKBBgj09g7cpqhgC1CKH4hEI1s+SZKFaNCiWOAtJW2JpfX5uGnATToiBCSMYyQQ+'
      'h1skDWTy6IwWlBKABBELZQIywDoA0A8Y1DRWKygGrJDOiAYiDSgWBNCDQg6BYwizrG7cNJo2FSt3PM+hYnTJks4IWKGFco3crAQE'
      'gea+tGaiAx1IkV5aisBEgAdKAyQJh7jwVJRECBHIHw+UXEElpFjpppElJSO9KYEQEw+IiwmiBFLBjcmolpygo4hn8fgcikAkxFDE'
      'mmuDoTEDmQyJBvYw6DiEAICiz1rMmNRczMCeFSSBQRHJBThpp+gMhBZDoABsPWxEfJCMbF7yrgAHaYEUl3RiZxhR8oL1xBABnGKz'
      'GSBQHJAEYRQNkkntJM1mIjKynahsVFQcQhEFjUkdYU5BCl/YnkQOgPKtt4Qa2VQxOB3A+KNYuzXOeIIFHBD1PGR7gYOPUN5SJ54c'
      '+I4zED0nHmp0wyvAHEcQLCUmpBYgkAKKKhryFZRAQcnkonCA6Qm9TO2EtKrGgacPE8gGMsh2XJoTNfER/ccmkglAxXI3jqouMdhl'
      '6d4jeHZieAgEkoa/CjK5GH69WJdoKEII8Mx6buUGMkuwOpIIYTLSqEaAFiRTpxFiAlKhBeDhNyFARRJzFwU0Q2BqhF/XEsAl1YBS'
      'CFEFQMVf0+KnAjDo1Prz+0lncA6MQrTRCGAV+OADyAHFCTcSAIQBTPIBoFYNO+wIuN74nYh1KIi2rlClCDpEI0nsRbClYWGi1CAk'
      'hxYuCtj7MkBIDsdXK/QfJeTSKRtbhfNpLBBB5IzRgYXKuGmQoQAAsfRbcMACPgxE0TFJQzCrslEUoMeaCiox54AIomUghVYdd8HD'
      'kLu0o2FZrx+UgtqjgW8L/dBjRSCpVmqphkRcCYWkED/mJH6APhleMkAdqQAYFdc7xg4EmgSFBUzPJgHP0mNw4eCqALBC+4KQQpg4'
      '48gdsAkNIUQrLbACHIBEcKSESoSRMimZqDRAw+iE2zZgBEoysM0kLQqElNtqIsKEnQCvnKArMPCogHBn0Qzq2QAxiCwASwQqlK0U'
      'AcQpQA8MF+yGcaghySgJUdiYleoLDBpVKEMSAUMHOzJAYLq1Ei34DTYBwShc4WkMBoEU0IWI5DqNJwQY+jl2EeFBjOKFyUIsRGSM'
      'CA3UAqfQoRuBEsGs8DhO0lWquxHFD4UBmRo3IlqF3XJaNm1gTOBGMucI4rQWCMtWNkGZMuafIxUZSH3QBBJR6RvcgKJNACSdJ4C0'
      'woT4IqcpNlPAwRiCGko3R1gi7WVQns4ItKw0KS8JwQQYwBQHx0UAsUu2YUgIIAAcktsZMACUCEzQQ3W1KEgiBFoEISVEI5Lc3O9n'
      'bCp1pSyG83ZGoEUD0JAK4nqAkCUGG7DQkNSwVAIAdhBcUoWY0hWwEYz3yGGEsGdkAUPoDuI/FFAoAS6CETzgXh1eIDsr8pEimPBC'
      'hYMciQAB67CgBwpgwBLEwGs7ocpOeAHE1gwGrAMGEOKjCgAJQoEMIBSs2jA0aPHoVHeW0KhweI22pP0AIOBQ9EhuK8NQIGAHerR7'
      'VoQxgeyMCusI7AzEBUTKISEOCxyjVs6qSEwHAQRQzI4AgNVVBdHgGgUapgPtUN1DB1BwMbBjNATZG+3KAxAQBDhBxdPhORAFGiLR'
      'lcNNCIFGTx0aubJIiZBPUFGMKydSzggPoARqaQcqVpRnoopMtlS26WYqcmQIHmR2gAIgZfJYYQEDPe4RmHaJHKE1IIDmMaMlUbse'
      'RAAhkIHwN0a5ZvyTRRtiMRUhawjggIgCEHTkg1iCht9AQKIpDiE1DwApFmSoYYxpB76ESJQgjCwCiQUc8t5DQqgkrFH6mByEkB4n'
      'QRRYC4OCUPCrEjQIbg6HER3YsQMidXCmCWQYEhWlT/BEzglKQiDdrNgVIh2mNSR4nr3BUjhxmQCmqWkQQQxmPEYNEhHK1nAk7NQA'
      'bgDJHADZygmiFEjBycQsJbgLCIoElqCrRfZu2kZjQJGSQ+EAUACSiieBAQDby4BtLBxgDUKs1PMwzwoCR0GiK7AsZGg+EFotwEgl'
      'BGtDE9vwCt0YdKHMQajARECgEYdBBRcAIUAdFRGPINvKADCgBEMM6AGFERajeAZBgCKGUCpPySChPuEKlA5D0gKGca8Aro+YCUAH'
      'FYGQghXym0CkS2uhjH8AChIRAUMQIBLwisKjC4MhYKmlRAo2f2yUGRIFDAamNnBAA21OAcD88AImM3RuHUOq8AhZBOdbGaLeaiqS'
      'FAICQ19RYiNsX5/KMJ1pphZ2ArqLA9ACioBgpolVR3TAZ+qMclni5TBTqsuOsELZLhyociYEWFlmIQxhdvAXiQ7OIQsAzg6MKbiM'
      'GwDBs0AWldihgz7ItCSADzCZkwgeVBPQzCeYcgdxiJ01gpmOEuJ7DPJgCCHlgQAIKU0QJcjJIX/FYBwcdpB2AlSNCpkcZB5GcUq0'
      'SFhwx9IAq+KDBUHLk0NASCjEwhKFYsVKTyRgFXTRjlEZEBhU8Iwu6XISwdGSmMhAceojSoR7CCAoKy5B8HsSQgXRNIM/IKwJy0TE'
      'yAA+ZyN1d4WweQ+BBFItCQvz5gkYAPWOJgRJ+pFp4XltetWdEJkwEJ8esJkENMDUoBkNeAR0CHhIyCNoFgBwkGFjpU8JMwGIYxmF'
      'IHJFwugHM6QgOQSxlHNFEBRGaGBfTRgHjE/Lgmy4wiujSmQU5GPzGjEYaNYkY9AQFLXiBgcYqjg0rjcygXOsElOYZwM+gmROqXjD'
      'MJyUwDwFCHmCROEkK1gYrhuCTDCJhd6JkyFiih0ZcCyzABphmIB4+LUzjiJ1EMyAjjcTjY6EvwCAglATSUBRIOFAv3pDIAMCBtCC'
      'w92ASfssUIDjCdDKpBoocwFOBE8iYUBbiSvoaQvYoBhTuTEwaJR/w1MVTRj4FI/VL8Fwzo6gr4c402xsERF8c8P2ACIYjVZcsQMN'
      'iomKNxChoElkYvlhJOVhyIelDBMkBKAcpdGRA8sAf0YxhA2BhjQdmBlUbIXC17FwADCL82AISCAThiCt6WEUlZzuKLPGiJytOoJ1'
      'U4MLkAICL+YrKo+3cNOo0IKyQFSU1zLQtEb4LoEMqxASQPBOi1lMA8mXD8w1POGImQZZjsAhPjJcJ+HZRlqFvlwIJ4VBBaaCA1i7'
      'jliADAMeVKfaJXZBE3EADMOQ4pIzhYJ2LZ8E4FOQoAInEdwUnFkLciHBAholcghaBMwhiQB4K8gGgs25d6OxpqQNKIA5KLlKURHD'
      'RcihaQ6EtChNE2BeT81UiLYFWyoP3dowo+hASuIUcQx/JgAthKACwDEQOgMN4wMuw7x877M2YNfWAEcecGhHm7kDXRWHOuDxJHrc'
      'VAbcUhQAJ28MTQdYGgI+GCgWtadIyAUVAq5U6JKpCENDWGruA8xIcKMjYVwESARotFFxGmBrlDyGCEYD0CYghUGkmxADbMRdlKDF'
      '1ApkIjYiWawUFK4sxV2ASG1A8QGxhk8SIOsRCbahdsfmAOpw6hhunSQAe7kdIokDwBs1MnFI8pIaCfL0AAsBXBAEhEUpsGOIyIkt'
      'gMpDfIgSNwZWnLopKQbsGG3zACQjvAFUpFjOKOoqYjJAwEuwUwHkM8kkHgEszA04EadaCwSBA2wEJzdKVqHKsMiIRSkO2IYJuCiv'
      '8RDAyU6IwgmKEXJIACyaSDvagWSkSjAxwoUsBhaKVtSQuAuali6kcChQI5GIAB5AzFPvG4sAHjWl73JChS+WjWAE+XZAqKGCAos3'
      'AY0F4gz4DQQcjgbB2B014M1G38XXAIF4mC0gxAIUFeAqHBYgmCaHyIfVAgAoaLUsh1XlwbxyWNe7hIaCOYZCINsgSxoCIqkgFAk6'
      'QkPBg+p4tQVjph/ZgGifAgJeEQIJmVBrGmIShlghEBM0AOIJkoQQgAiRMoR0rIIQ8548TBEQknAYxOItNS5kQMARHSCBW1QBMx3n'
      'hFs1NiYi8AQAAsDAWMJ0JgBCwQtNI7m3F1KSYS+Y2VDLaXMYFcIWBBavjQ0wtVI7DAWmAXD1ybGC1/XwumqJDq52hz1kJ4AHUEMV'
      'hJwbAhQsJeVJACTd0BQBy8IIkUBC21CjHBiEsAUMQA4iphDJynnRXXTaGHGOCrpWzWQxwiEKwhBPrItCtR5dJAKPGlF5/Eio4GxU'
      'j0b3ns5GSljqkhEDV7CAq85Ag9qBw7AIGjiiGcjcUELBCgChah6yccH/whLGU4VUgpAcocj3ygZPU2QIQAhUqGpYQKVDAEzgrgJQ'
      'RpGpgBCHVaOMMccgUrQtckDMgAkl4MACp+SYlBWCQKmoq3qqaG0oMYoIBHIhUQlulIQT+VMo4ANiuCyJE5oJA7KhXqFVMLZGOxg1'
      'mXGQ+csJSZwQGX1lgk45QDwDw6GYmCfAAQaNvjaWIgkAQRAG6dJxYgWirGGZKlpwSz8DBpCPuAAZEsJ0lhYYKO2psFUiHASIKLGW'
      'rK5iIE3os8lQcAtKHBhQ3eqAhEWRmKgsHECAyFglDviCQwCpVmS6JYLhobB4vA8iMi2gKejZ8IxDrPEQCSMly4PWXQwp9qK6AAjS'
      'AaCCiSHEbVJ2AjbNGBHoJDSowB09gAZM8gwPOhTcEaCg9yopQAhIgSNcw1gYrEYehEJ5WBDYA0HMcbLBaWJr4FoNp0BPkKJQEQCI'
      'mQB0JmHSBaB4lCpShQMSkbPAmalGoDLQOZF4o29RtIyYCKggffgURNi76zpGSWBCoDCYZZmFI1artJRTrvRSVSmqn8AIiVCNAUsI'
      '+eHhCE6q7FIQxEJuDZMRCDaERXJGl2UJWaWPlFaBMsRzLO4GqHOBQTgwpYBsxZLtkxmxQWXbmEoMRMSPqABeBKo4JDMQBHFDUIAr'
      'ImQXFaRmgyHdNANcYqMSJAKKUQ22PnWHKzRpMToJoxEIoMnmmGKAudLMGBow/SOCYBhDlaEgEqcGE3LBcgBKJs4CTngUoZhpSGHR'
      'oQcCAGoNkIIFwA2jApy/JIERDCoSZ00Nqg+YPKGhikekq5UdDDktoBcCJAEoB9USiBCQgCIBjnM5Jj8WMJS6ozMC1WjLRSCkxkYi'
      'EQCkCmwWRASYUfwtNxjLihZiSeC8wuChFLAMGRYBUoFiJhYuljZsIWlRK4skbG8YZKqIt0IjpJgMu8B7bxHJYY6gDxGyX7GBIFVh'
      'EBnslcBAzFNjS6VDIiq4IxgmgEBgID//ToKAkYVgMAIEry1BmFEbigPJZHNDLTHpmZkXDRpMWACpwqzoQR9ZZELAgGWIJuQIBsF9'
      'kkJ9Mfrg3hxXcaK5AfrEtrUEY7bEhCIVoBSsuiBpAK4MKOO9qYUxlHYoxsocxAZOKyQZUs+gKQuGbXUGL4PXAVJsQaJGLu8f9RNH'
      'Q1irJR0rwdP/vytKUJg2lvRD4aI0QtRIr0oBAyetESQyBqapyFigMUnvRkxoXbCZAhM2IcUAFK0oTEQggOEhjXFG5oBbuuoYQjDG'
      'SEDRwCZmUajAquud06YP354cmwZjKqjlvjKKEMZaZVAF1Wc1qUu18FEQojdxZIMZC0jUsTkCheyKgFEvpDUMoIiYvZknAAxJHpFI'
      'pBGC4cAcIQDGJHws5ekBiOQgohAXWJrnOFBeMsFInMVMCT71yCucJkYONZcghgHiaCkRoKDZGmKdBX8QBgKoeeYAg7hG76mdXAmI'
      'mcICkeKEOpQFxg/FfYAGYXmD0VAzGCaxxZSECgwBbpBH8xCAJW0dpFiZhDJkCyAANmCNu/dyZAEcWFP8v1vaXH77eFHWqdF0z3NU'
      'KqIzbjEAgIna7NJ0CT6B3yDeARwBulqANjEmCEIa3hDrJCAg0VYI02/mAecYHANIhHIjeIsyW6wAtCPFgF55g9yGVmheKqE2Pnnb'
      'DHQwm8yFhAEAALhIyIFDQ1UFlRy7xFHKEcSDrEKwEjZMERJBBBKcFA8clAKbjBD6RXhjeEASQECJj8ANwsMYWaRVmahsTkmAA0kc'
      '6tCZR8ImCBX5F8iWrtR4wMjLuglLFpnCxILBhQHGTIIRsHIQMqI/wBSgAGSUpdH7eg1SGEDnJCxUQwdxKTRCysvIQJq+HoSKJAbY'
      'BoBr1OXQpJeACYMb41DJ3SxsAHzCSGIwFwRAgzirBSKWCrh9wEIGJGEHBD3CeZLAMCjheDqBUiDEeIvOK+Kq5QGyKpdTzIP+rUZm'
      'RpjFDGwiEERgB+YNcuePjAlvnTZGoJcCJwpR5CoqXwcAeJpAEqp8RCAxxH1IA2PhEdJBMuLHiGsjL2AcEMHsYDFZQkGhDcDg1TIg'
      '8wXRSlGgFg49IQxLCxITiJBkxf+xIEBxDliLZJQhQBAAtEJyA3ZC8OuRIFe9bgK0Ao0ujiiuBowADTI3IgNpcjt5jG1w0HMEn0Kh'
      'tVAODAN5pEgXIASQwroaGAVM5MMxADGQNgscADjqojyqGcWI0FTDQgaKoVxy3gvQDDXkAv5KWawEzAw0iJMqzCqAJlgmAhgJIiRF'
      '8QJ7GqmQzDRZhwjYSxowOlAka4Gdew2UdXhBBO1YIEQOIi2kwvXmqo8ZPL1s8+TNh0uqWLcYQ6ph0JIOSsGBIGzGdkCAuCRwqWSU'
      'Q4oLgwhEI/2ciC0AFPYCdjhU1EB6LREZ1h596Tgx+6E0soiYBAoNSMe5600jWFlmgiHgngc3hVThfjEPCPwS/EQzOUehGROXqLng'
      'uBEJUfUFGWApsMiR3TKJuK9jn10ZaHwI5kBhS/9LeERqCNRsAiJCipRd0VufTIARMYRccIIlpSVz0kIVAopwJQzgAKTTfj5lC0cM'
      'MrpSEQeALhC4sPciQKUdBpQwgEBkRQkpGqDCKYnRvIGkMsAI9BzQRgPzgEKR8AMQNFwgsFsCbg8wsF1gUkIHbS6JVZhgUIyVoWdy'
      'gjAbkL1GTmLhhwagdAcnCtJlqJJCjW1yzwDymKJexqCtYuS4K0PzAhIpYGzdNDu8phb8pWQvfqACRpVQM0aiphIvKrQQhkoyETKg'
      'Nax3hAdqMGrMmLe8qQmaQwDIAyVrY17VzokyTRSGqcKGIuLSRoXI4EV9QtVahKkPNpwoLSKvJC+auKNCiEhxhENN7Cu8MVM2nDK/'
      'tAiiGUD3AhxAg/NyBILKWJsZsThEvabNjBTNUkVQEE8yMyAIow2EgckCJXGsOo0X1cmjgBHrABsNIMiWbG6DQNvBUMjQcBaOzQ1g'
      'NLyUzfUiWgYiVUS+Sh0ESZuNJIaQNNgKCiqPEMxnnOh1gdcNFeIYpFvqzmTo5HUPsoS/KZiFEME3kGVWZIOJuCbMogreMjQrI8wI'
      'dY0CscOgAjBABqRIAHhAghNxyGB0DoFscJqCrHamzhAXefQcQSBUBlSEgBHAKyAoB8cm2DRTgDKUYwHrB05Uhw0nnxmTxAqQMpWh'
      'uCoGEgYUZKtn0BSRKGUUkWRnPcUWcCVgKuzSaIjWx+wa8A0OAFYFAJ/wjgaCTBVxJxEvIgqDQgwAShEDl0tAYG7M+BHSBgFfFYC6'
      'TKQpGEA5cKWAXISFME9UxhE6RiFW0pwAFBRpGutaK6QkNwVA7CCB6ZBiACRWCvMH+Yn8AE1LwlzoJMF53gaBIGaJEATNVEiB1hBY'
      'ICkjQ082o9hKlcORnIhUtTsCyWZIkJBYAUjQpCAIKFgtVikBZyKfAMReVZwjIEC6EUWYUCKDkvjPgoW4K2BRMD4QJQFCMFvK22hx'
      '0iIZwyLBSCjSUJFvpIZXAu5wgJzz6AKuILEKvXKpQGHNGYgGhMEoE7kcENllFoBgEirQQSBopM4BIdBtySIGJVQIwQUg4jaMZwBg'
      'ftjqn6MCRXuSMUbrnmNhAnihACloEFJBsMsGPpUIxXSBThqQwOcDLRZsCKaqAGSxIUoDCgoJs1Ep8MwDFVPRHBnAl49KA0HZJFcG'
      'gCnpQMNxt7EMZloYDdycoJ2KRJOMaAbGg9DwKcMAFyexzSkBMMxDLQAtMUPYeaCBh6QmUos0VcGwARAGGJaXkvEBCRsPHGMkJAaB'
      'XoMGQdALItRBI4aCkEXkLSISI/YAg4VJx5HlQWgIDiIPgDHgGNqkZ0xEfi/xesHIqbcUYIFA/MWLLNgArKUNyJYFGke0REKp4tcw'
      'EkMBaplyiYK+hmEO4EJrSgNkoiIgACYING4Jm9BZszgXgg1am+LZlNRJiCLcuYOHII9QuyDD/BcBlSYgwl0rfpAbITA5WSwAwjgM'
      'lM+cArRWQ4EBD13AgFpbFE1UG/Cx2SkxYgFSlDc5YgoYlRPf2B4ApQ0V4HAA0AICAIJI';
}

typedef _SpellCheckFieldBuilder = Widget Function(
  SpellCheckConfiguration configuration,
);

class _FocusedSpellCheck extends StatefulWidget {
  const _FocusedSpellCheck({required this.enabled, required this.builder});

  final bool enabled;
  final _SpellCheckFieldBuilder builder;

  @override
  State<_FocusedSpellCheck> createState() => _FocusedSpellCheckState();
}

class _FocusedSpellCheckState extends State<_FocusedSpellCheck> {
  final _fieldKey = GlobalKey();
  _FocusAwareSpellCheckService? _service;
  bool _hasFocus = false;
  int _focusGeneration = 0;

  @override
  void initState() {
    super.initState();
    _configureService();
  }

  @override
  void didUpdateWidget(_FocusedSpellCheck oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (widget.enabled != oldWidget.enabled) _configureService();
  }

  void _configureService() {
    final nativeSpellCheckAvailable = WidgetsBinding
        .instance
        .platformDispatcher
        .nativeSpellCheckServiceDefined;
    final SpellCheckService? baseService = kIsWeb
        ? _browserEnglishSpellChecker
        : nativeSpellCheckAvailable
        ? DefaultSpellCheckService()
        : null;
    _service = widget.enabled && baseService != null
        ? _FocusAwareSpellCheckService(baseService)
        : null;
    _service?.focused = _hasFocus;
  }

  void _handleFocusChange(bool hasFocus) {
    _hasFocus = hasFocus;
    _service?.focused = hasFocus;
    final generation = ++_focusGeneration;
    WidgetsBinding.instance.addPostFrameCallback((_) {
      if (mounted && generation == _focusGeneration) {
        _updateUnderline(hasFocus, generation);
      }
    });
  }

  Future<void> _updateUnderline(bool show, int generation) async {
    final editable = _findEditableTextState();
    if (editable == null) return;

    if (!show) {
      editable.spellCheckResults = null;
      editable.renderEditable.text = editable.buildTextSpan();
      return;
    }

    final service = _service;
    final text = editable.textEditingValue.text;
    if (service == null || text.isEmpty) return;

    final results = await service.fetchSpellCheckSuggestions(
      Localizations.maybeLocaleOf(context) ?? const Locale('en'),
      text,
    );
    if (!mounted ||
        !_hasFocus ||
        generation != _focusGeneration ||
        editable.textEditingValue.text != text) {
      return;
    }

    editable.spellCheckResults = SpellCheckResults(
      text,
      results ?? const <SuggestionSpan>[],
    );
    editable.renderEditable.text = editable.buildTextSpan();
  }

  EditableTextState? _findEditableTextState() {
    final fieldContext = _fieldKey.currentContext;
    if (fieldContext == null) return null;

    EditableTextState? result;
    void visit(Element element) {
      if (result != null) return;
      if (element is StatefulElement && element.state is EditableTextState) {
        result = element.state as EditableTextState;
        return;
      }
      element.visitChildElements(visit);
    }

    (fieldContext as Element).visitChildElements(visit);
    return result;
  }

  @override
  Widget build(BuildContext context) {
    final service = _service;
    final configuration = service == null
        ? const SpellCheckConfiguration.disabled()
        : SpellCheckConfiguration(
            spellCheckService: service,
            misspelledTextStyle: const TextStyle(
              decoration: TextDecoration.underline,
              decorationColor: Colors.red,
              decorationStyle: TextDecorationStyle.wavy,
            ),
          );

    return Focus(
      canRequestFocus: false,
      skipTraversal: true,
      onFocusChange: _handleFocusChange,
      child: KeyedSubtree(
        key: _fieldKey,
        child: widget.builder(configuration),
      ),
    );
  }
}

class _FocusAwareSpellCheckService implements SpellCheckService {
  _FocusAwareSpellCheckService(this._service);

  final SpellCheckService _service;
  bool isFocused = false;
  int _focusGeneration = 0;

  @override
  Future<List<SuggestionSpan>?> fetchSpellCheckSuggestions(
    Locale locale,
    String text,
  ) async {
    if (!isFocused) return const <SuggestionSpan>[];
    final generation = _focusGeneration;
    final results = await _service.fetchSpellCheckSuggestions(locale, text);
    if (!isFocused || generation != _focusGeneration) {
      return const <SuggestionSpan>[];
    }
    return results;
  }

  set focused(bool value) {
    if (isFocused == value) return;
    isFocused = value;
    _focusGeneration++;
  }
}

Widget myTextFormFieldWithBorder({
  String? labelText,
  String? hintText,
  TextEditingController? controller,
  bool? validate,
  bool obscureText = false,
  Widget? suffixIcon,
  Icon? icon,
  bool? isnumber,
  bool? isDouble,
  bool? isDate,
  double? width,
  String? initialValue,
  bool? isCapitaLetters,
  FocusNode? focusNode,
  FocusNode? nextFocusNode,
  bool? moneyFormat,
  TextInputAction? textInputAction,
  void Function()? onEditingComplete,
  maxLines = 1,
  TextAlign? textAlign = TextAlign.start,
  int? minLines,
  TextInputType? keyboardType,
  void Function(String)? onChanged,
  void Function(String)? onFieldSubmitted,
  bool? isEnabled = true,
  void Function(PointerDownEvent)? onTapOutside,
  bool? readOnly,
  FocusNode? previousFocusNode,
}) {
  return SizedBox(
    width: width,
    child: Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        labelText != null
            ? Padding(
                padding: const EdgeInsets.only(left: 2),
                child: Text(
                  overflow: TextOverflow.ellipsis,
                  labelText,
                  style: textFieldLabelStyle,
                ),
              )
            : const SizedBox(),
        Focus(
          canRequestFocus: false,
          skipTraversal: true,
          onKeyEvent: (node, event) {
            if (event is! KeyDownEvent) return KeyEventResult.ignored;
            if (event.logicalKey != LogicalKeyboardKey.tab) {
              return KeyEventResult.ignored;
            }

            final isShift = HardwareKeyboard.instance.isShiftPressed;

            if (isShift) {
              if (previousFocusNode != null) {
                previousFocusNode.requestFocus();
                return KeyEventResult.handled;
              }
              return KeyEventResult.ignored; // default back traversal
            } else {
              if (nextFocusNode != null) {
                nextFocusNode.requestFocus();
                return KeyEventResult.handled;
              }
              return KeyEventResult.ignored; // default forward traversal
            }
          },
          child: _FocusedSpellCheck(
            enabled:
                !obscureText &&
                isnumber != true &&
                isDouble != true &&
                isDate != true &&
                moneyFormat != true &&
                keyboardType != TextInputType.emailAddress &&
                keyboardType != TextInputType.url &&
                keyboardType != TextInputType.phone,
            builder: (spellCheckConfiguration) => TextFormField(
              spellCheckConfiguration: spellCheckConfiguration,
              initialValue: initialValue,
              canRequestFocus: true,
              readOnly: readOnly ?? false,
              onTapOutside: onTapOutside,
              onEditingComplete: onEditingComplete,
              textInputAction: textInputAction,
              focusNode: focusNode,
              onFieldSubmitted: (v) {
                if (nextFocusNode != null) {
                  nextFocusNode.requestFocus();
                }
                onFieldSubmitted?.call(v);
              },
              textAlign: textAlign!,
              style: textFieldFontStyle,
              minLines: minLines,
              maxLines: maxLines,
              onChanged: onChanged,
              inputFormatters: isnumber == true
                  ? [FilteringTextInputFormatter.digitsOnly]
                  : isDouble == true
                  ? [DecimalTextInputFormatter()]
                  : isDate == true
                  ? [DateTextFormatter()]
                  : isCapitaLetters == true
                  ? [CapitalLettersOnlyFormatter()]
                  : moneyFormat == true
                  ? [CurrencyInputFormatter()]
                  : null,
              enabled: isEnabled,
              obscureText: obscureText,
              keyboardType: keyboardType,
              controller: controller,
              decoration: InputDecoration(
                contentPadding: const EdgeInsets.symmetric(
                  horizontal: 10,
                  vertical: !kIsWeb ? 7 : 11,
                ),
                isDense: true,
                icon: icon,
                suffixIcon: ExcludeFocus(child: suffixIcon ?? const SizedBox()),
                suffixIconConstraints: const BoxConstraints(
                  maxHeight: 30,
                  maxWidth: 40,
                ),
                prefixIconConstraints: const BoxConstraints(
                  maxHeight: 15,
                  maxWidth: 15,
                ),
                hintStyle: const TextStyle(color: Colors.grey, fontSize: 14),
                // labelText: labelText,
                alignLabelWithHint: true,

                hintText: hintText,
                labelStyle: TextStyle(
                  color: isEnabled == false
                      ? Colors.grey.shade500
                      : Colors.grey.shade700,
                ),
                fillColor: isEnabled == true
                    ? Colors.white
                    : Colors.grey.shade200,
                filled: true,
                // focusedBorder: const OutlineInputBorder(
                //   // borderRadius: BorderRadius.circular(borderRadius!),
                //   borderSide: BorderSide(color: Colors.grey, width: 2.0),
                // ),
                enabledBorder: const OutlineInputBorder(
                  // borderRadius: BorderRadius.circular(borderRadius),
                  borderSide: BorderSide(color: Colors.grey, width: 1.0),
                ),
                disabledBorder: OutlineInputBorder(
                  // borderRadius: BorderRadius.circular(borderRadius),
                  borderSide: BorderSide(color: Colors.grey.shade400, width: 1.0),
                ),
                errorBorder: const OutlineInputBorder(
                  // borderRadius: BorderRadius.circular(5),
                  borderSide: BorderSide(color: Colors.red, width: 1.0),
                ),
                focusedErrorBorder: const OutlineInputBorder(
                  // borderRadius: BorderRadius.circular(5),
                  borderSide: BorderSide(color: Colors.red, width: 2.0),
                ),
              ),
              validator: validate != false
                  ? (value) {
                      if (value!.isEmpty) {
                        return 'Please Enter $labelText';
                      }
                      return null;
                    }
                  : null,
            ),
          ),
        ),
      ],
    ),
  );
}


 // focusNode: focusNode,
          // onKeyEvent: (node, event) {
          //   if (event is KeyDownEvent &&
          //       (event.logicalKey == LogicalKeyboardKey.tab ||
          //           event.logicalKey == LogicalKeyboardKey.enter)) {
          //     onFieldSubmitted?.call('');

          //     if (nextFocusNode != null) {
          //       nextFocusNode.requestFocus();
          //     }
          //     return KeyEventResult.handled;
          //   } else if (event is KeyDownEvent &&
          //       event.logicalKey == LogicalKeyboardKey.shift) {}
          //   return KeyEventResult.ignored;
          // },